# This file generates GDML files according to the coordinates provided by the
# 'Detector Coordinates.txt' file. The text to write out was generated by
# the 'GDML conversion' Jupyter notebook.
import numpy as np

dest = "/Users/AndyB/Documents/School/Berkeley/Simulations/LabDose/Scripts"

coords = np.loadtxt(dest + '/' + 'Detector Coordinates.txt', skiprows=2)
name = "BirgeLab"

for i in range(0, len(coords)):
	xpos = coords[i,0]
	ypos = coords[i,1]
	zpos = coords[i,2]

	filetext = '<?xml version="1.0" encoding="UTF-8" standalone="no" ?>\n' + \
'<gdml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://service-spi.web.cern.ch/service-spi/app/releases/GDML/schema/gdml.xsd">\n' + \
'\n' + \
'  <define/>\n' + \
'\n' + \
'  <materials>\n' + \
'    <isotope N="1" Z="1" name="H10x7fed4fc83d90">\n' + \
'      <atom unit="g/mole" value="1.00782503081372"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="2" Z="1" name="H20x7fed4fc83ed0">\n' + \
'      <atom unit="g/mole" value="2.01410199966617"/>\n' + \
'    </isotope>\n' + \
'    <element name="H0x7fed4fc83f20">\n' + \
'      <fraction n="0.999885" ref="H10x7fed4fc83d90"/>\n' + \
'      <fraction n="0.000115" ref="H20x7fed4fc83ed0"/>\n' + \
'    </element>\n' + \
'    <isotope N="12" Z="6" name="C120x7fed4fc84280">\n' + \
'      <atom unit="g/mole" value="12"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="13" Z="6" name="C130x7fed4fc842e0">\n' + \
'      <atom unit="g/mole" value="13.0034"/>\n' + \
'    </isotope>\n' + \
'    <element name="C0x7fed4fc84a30">\n' + \
'      <fraction n="0.9893" ref="C120x7fed4fc84280"/>\n' + \
'      <fraction n="0.0107" ref="C130x7fed4fc842e0"/>\n' + \
'    </element>\n' + \
'    <isotope N="16" Z="8" name="O160x7fed4fc84e60">\n' + \
'      <atom unit="g/mole" value="15.9949"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="17" Z="8" name="O170x7fed4fc84ea0">\n' + \
'      <atom unit="g/mole" value="16.9991"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="18" Z="8" name="O180x7fed4fc84ee0">\n' + \
'      <atom unit="g/mole" value="17.9992"/>\n' + \
'    </isotope>\n' + \
'    <element name="O0x7fed4fc84fc0">\n' + \
'      <fraction n="0.99757" ref="O160x7fed4fc84e60"/>\n' + \
'      <fraction n="0.00038" ref="O170x7fed4fc84ea0"/>\n' + \
'      <fraction n="0.00205" ref="O180x7fed4fc84ee0"/>\n' + \
'    </element>\n' + \
'    <isotope N="23" Z="11" name="Na230x7fed4fc87fc0">\n' + \
'      <atom unit="g/mole" value="22.9898"/>\n' + \
'    </isotope>\n' + \
'    <element name="Na0x7fed4fc88410">\n' + \
'      <fraction n="1" ref="Na230x7fed4fc87fc0"/>\n' + \
'    </element>\n' + \
'    <isotope N="24" Z="12" name="Mg240x7fed4fc97440">\n' + \
'      <atom unit="g/mole" value="23.985"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="25" Z="12" name="Mg250x7fed4fc96e30">\n' + \
'      <atom unit="g/mole" value="24.9858"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="26" Z="12" name="Mg260x7fed4fc96e70">\n' + \
'      <atom unit="g/mole" value="25.9826"/>\n' + \
'    </isotope>\n' + \
'    <element name="Mg0x7fed4fc96ed0">\n' + \
'      <fraction n="0.7899" ref="Mg240x7fed4fc97440"/>\n' + \
'      <fraction n="0.1" ref="Mg250x7fed4fc96e30"/>\n' + \
'      <fraction n="0.1101" ref="Mg260x7fed4fc96e70"/>\n' + \
'    </element>\n' + \
'    <isotope N="27" Z="13" name="Al270x7fed4fc87710">\n' + \
'      <atom unit="g/mole" value="26.9815"/>\n' + \
'    </isotope>\n' + \
'    <element name="Al0x7fed4fc87c40">\n' + \
'      <fraction n="1" ref="Al270x7fed4fc87710"/>\n' + \
'    </element>\n' + \
'    <isotope N="28" Z="14" name="Si280x7fed4fc885e0">\n' + \
'      <atom unit="g/mole" value="27.9769"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="29" Z="14" name="Si290x7fed4fc88620">\n' + \
'      <atom unit="g/mole" value="28.9765"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="30" Z="14" name="Si300x7fed4fc88670">\n' + \
'      <atom unit="g/mole" value="29.9738"/>\n' + \
'    </isotope>\n' + \
'    <element name="Si0x7fed4fc886d0">\n' + \
'      <fraction n="0.922296077703922" ref="Si280x7fed4fc885e0"/>\n' + \
'      <fraction n="0.0468319531680468" ref="Si290x7fed4fc88620"/>\n' + \
'      <fraction n="0.0308719691280309" ref="Si300x7fed4fc88670"/>\n' + \
'    </element>\n' + \
'    <isotope N="39" Z="19" name="K390x7fed4fc94060">\n' + \
'      <atom unit="g/mole" value="38.9637"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="40" Z="19" name="K400x7fed4fc940a0">\n' + \
'      <atom unit="g/mole" value="39.964"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="41" Z="19" name="K410x7fed4fc940e0">\n' + \
'      <atom unit="g/mole" value="40.9618"/>\n' + \
'    </isotope>\n' + \
'    <element name="K0x7fed4fc94140">\n' + \
'      <fraction n="0.932581" ref="K390x7fed4fc94060"/>\n' + \
'      <fraction n="0.000117" ref="K400x7fed4fc940a0"/>\n' + \
'      <fraction n="0.067302" ref="K410x7fed4fc940e0"/>\n' + \
'    </element>\n' + \
'    <isotope N="40" Z="20" name="Ca400x7fed4fc888d0">\n' + \
'      <atom unit="g/mole" value="39.9626"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="42" Z="20" name="Ca420x7fed4fc88910">\n' + \
'      <atom unit="g/mole" value="41.9586"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="43" Z="20" name="Ca430x7fed4fc88950">\n' + \
'      <atom unit="g/mole" value="42.9588"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="44" Z="20" name="Ca440x7fed4fc88990">\n' + \
'      <atom unit="g/mole" value="43.9555"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="46" Z="20" name="Ca460x7fed4fc889d0">\n' + \
'      <atom unit="g/mole" value="45.9537"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="48" Z="20" name="Ca480x7fed4fc86a30">\n' + \
'      <atom unit="g/mole" value="47.9525"/>\n' + \
'    </isotope>\n' + \
'    <element name="Ca0x7fed4fc88c10">\n' + \
'      <fraction n="0.96941" ref="Ca400x7fed4fc888d0"/>\n' + \
'      <fraction n="0.00647" ref="Ca420x7fed4fc88910"/>\n' + \
'      <fraction n="0.00135" ref="Ca430x7fed4fc88950"/>\n' + \
'      <fraction n="0.02086" ref="Ca440x7fed4fc88990"/>\n' + \
'      <fraction n="4e-05" ref="Ca460x7fed4fc889d0"/>\n' + \
'      <fraction n="0.00187" ref="Ca480x7fed4fc86a30"/>\n' + \
'    </element>\n' + \
'    <isotope N="54" Z="26" name="Fe540x7fed4fc8d5b0">\n' + \
'      <atom unit="g/mole" value="53.9396"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="56" Z="26" name="Fe560x7fed4fc8d0b0">\n' + \
'      <atom unit="g/mole" value="55.9349"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="57" Z="26" name="Fe570x7fed4fc8d0f0">\n' + \
'      <atom unit="g/mole" value="56.9354"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="58" Z="26" name="Fe580x7fed4fc8d150">\n' + \
'      <atom unit="g/mole" value="57.9333"/>\n' + \
'    </isotope>\n' + \
'    <element name="Fe0x7fed4fc8d190">\n' + \
'      <fraction n="0.05845" ref="Fe540x7fed4fc8d5b0"/>\n' + \
'      <fraction n="0.91754" ref="Fe560x7fed4fc8d0b0"/>\n' + \
'      <fraction n="0.02119" ref="Fe570x7fed4fc8d0f0"/>\n' + \
'      <fraction n="0.00282" ref="Fe580x7fed4fc8d150"/>\n' + \
'    </element>\n' + \
'    <material name="G4_CONCRETE0x7fed4fca2da0" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="135.2"/>\n' + \
'      <D unit="g/cm3" value="2.3"/>\n' + \
'      <fraction n="0.01" ref="H0x7fed4fc83f20"/>\n' + \
'      <fraction n="0.001" ref="C0x7fed4fc84a30"/>\n' + \
'      <fraction n="0.529107" ref="O0x7fed4fc84fc0"/>\n' + \
'      <fraction n="0.016" ref="Na0x7fed4fc88410"/>\n' + \
'      <fraction n="0.002" ref="Mg0x7fed4fc96ed0"/>\n' + \
'      <fraction n="0.033872" ref="Al0x7fed4fc87c40"/>\n' + \
'      <fraction n="0.337021" ref="Si0x7fed4fc886d0"/>\n' + \
'      <fraction n="0.013" ref="K0x7fed4fc94140"/>\n' + \
'      <fraction n="0.044" ref="Ca0x7fed4fc88c10"/>\n' + \
'      <fraction n="0.014" ref="Fe0x7fed4fc8d190"/>\n' + \
'    </material>\n' + \
'    <material name="wood0x7fed4fc97d30" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="67.1996868607977"/>\n' + \
'      <D unit="g/cm3" value="0.9"/>\n' + \
'      <fraction n="0.0915215132472401" ref="H0x7fed4fc83f20"/>\n' + \
'      <fraction n="0.363188118343343" ref="O0x7fed4fc84fc0"/>\n' + \
'      <fraction n="0.545290368409417" ref="C0x7fed4fc84a30"/>\n' + \
'    </material>\n' + \
'    <material name="Al60610x7fed4fc96d40" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="166.28607227249"/>\n' + \
'      <D unit="g/cm3" value="2.7"/>\n' + \
'      <fraction n="0.98" ref="Al0x7fed4fc87c40"/>\n' + \
'      <fraction n="0.01" ref="Mg0x7fed4fc96ed0"/>\n' + \
'      <fraction n="0.006" ref="Si0x7fed4fc886d0"/>\n' + \
'      <fraction n="0.004" ref="Fe0x7fed4fc8d190"/>\n' + \
'    </material>\n' + \
'    <material name="Soil0x7fed4fc96a70" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="112.098510188939"/>\n' + \
'      <D unit="g/cm3" value="1.5"/>\n' + \
'      <fraction n="0.021" ref="H0x7fed4fc83f20"/>\n' + \
'      <fraction n="0.016" ref="C0x7fed4fc84a30"/>\n' + \
'      <fraction n="0.577" ref="O0x7fed4fc84fc0"/>\n' + \
'      <fraction n="0.05" ref="Al0x7fed4fc87c40"/>\n' + \
'      <fraction n="0.271" ref="Si0x7fed4fc886d0"/>\n' + \
'      <fraction n="0.013" ref="K0x7fed4fc94140"/>\n' + \
'      <fraction n="0.041" ref="Ca0x7fed4fc88c10"/>\n' + \
'      <fraction n="0.011" ref="Fe0x7fed4fc8d190"/>\n' + \
'    </material>\n' + \
'    <isotope N="3" Z="2" name="He30x7fed4fc9d860">\n' + \
'      <atom unit="g/mole" value="3.01692961808401"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="4" Z="2" name="He40x7fed4fc9d8a0">\n' + \
'      <atom unit="g/mole" value="4.00264393551385"/>\n' + \
'    </isotope>\n' + \
'    <element name="He0x7fed4fc9d750">\n' + \
'      <fraction n="1.36999949310019e-06" ref="He30x7fed4fc9d860"/>\n' + \
'      <fraction n="0.999998630000507" ref="He40x7fed4fc9d8a0"/>\n' + \
'    </element>\n' + \
'    <material name="liquid_helium0x7fed4fc9d640" state="liquid">\n' + \
'      <T unit="K" value="3"/>\n' + \
'      <MEE unit="eV" value="41.8"/>\n' + \
'      <D unit="g/cm3" value="0.141"/>\n' + \
'      <fraction n="1" ref="He0x7fed4fc9d750"/>\n' + \
'    </material>\n' + \
'    <isotope N="12" Z="6" name="C120x7fed4fc9a5e0">\n' + \
'      <atom unit="g/mole" value="12"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="13" Z="6" name="C130x7fed4fc9a8e0">\n' + \
'      <atom unit="g/mole" value="13.0034"/>\n' + \
'    </isotope>\n' + \
'    <element name="Carbon0x7fed4fc9a830">\n' + \
'      <fraction n="0.9893" ref="C120x7fed4fc9a5e0"/>\n' + \
'      <fraction n="0.0107" ref="C130x7fed4fc9a8e0"/>\n' + \
'    </element>\n' + \
'    <isotope N="55" Z="25" name="Mn550x7fed4fc9ca40">\n' + \
'      <atom unit="g/mole" value="54.938"/>\n' + \
'    </isotope>\n' + \
'    <element name="Manganese0x7fed4fc9c8e0">\n' + \
'      <fraction n="1" ref="Mn550x7fed4fc9ca40"/>\n' + \
'    </element>\n' + \
'    <isotope N="31" Z="15" name="P310x7fed4fc9c0c0">\n' + \
'      <atom unit="g/mole" value="30.9738"/>\n' + \
'    </isotope>\n' + \
'    <element name="Phosphorus0x7fed4fc9bf80">\n' + \
'      <fraction n="1" ref="P310x7fed4fc9c0c0"/>\n' + \
'    </element>\n' + \
'    <isotope N="32" Z="16" name="S320x7fed4fc9c300">\n' + \
'      <atom unit="g/mole" value="31.9721"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="33" Z="16" name="S330x7fed4fc9c340">\n' + \
'      <atom unit="g/mole" value="32.9715"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="34" Z="16" name="S340x7fed4fc9c380">\n' + \
'      <atom unit="g/mole" value="33.9679"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="36" Z="16" name="S360x7fed4fc9c3c0">\n' + \
'      <atom unit="g/mole" value="35.9671"/>\n' + \
'    </isotope>\n' + \
'    <element name="Sulfur0x7fed4fc9c1a0">\n' + \
'      <fraction n="0.9493" ref="S320x7fed4fc9c300"/>\n' + \
'      <fraction n="0.0076" ref="S330x7fed4fc9c340"/>\n' + \
'      <fraction n="0.0429" ref="S340x7fed4fc9c380"/>\n' + \
'      <fraction n="0.0002" ref="S360x7fed4fc9c3c0"/>\n' + \
'    </element>\n' + \
'    <isotope N="28" Z="14" name="Si280x7fed4fc9be20">\n' + \
'      <atom unit="g/mole" value="27.9769"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="29" Z="14" name="Si290x7fed4fc9be60">\n' + \
'      <atom unit="g/mole" value="28.9765"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="30" Z="14" name="Si300x7fed4fc9bea0">\n' + \
'      <atom unit="g/mole" value="29.9738"/>\n' + \
'    </isotope>\n' + \
'    <element name="Silicon0x7fed4fc9bcc0">\n' + \
'      <fraction n="0.922296077703922" ref="Si280x7fed4fc9be20"/>\n' + \
'      <fraction n="0.0468319531680468" ref="Si290x7fed4fc9be60"/>\n' + \
'      <fraction n="0.0308719691280309" ref="Si300x7fed4fc9bea0"/>\n' + \
'    </element>\n' + \
'    <isotope N="50" Z="24" name="Cr500x7fed4fc9c740">\n' + \
'      <atom unit="g/mole" value="49.946"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="52" Z="24" name="Cr520x7fed4fc9c780">\n' + \
'      <atom unit="g/mole" value="51.9405"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="53" Z="24" name="Cr530x7fed4fc9c7c0">\n' + \
'      <atom unit="g/mole" value="52.9407"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="54" Z="24" name="Cr540x7fed4fc9c800">\n' + \
'      <atom unit="g/mole" value="53.9389"/>\n' + \
'    </isotope>\n' + \
'    <element name="Chromium0x7fed4fc9c600">\n' + \
'      <fraction n="0.04345" ref="Cr500x7fed4fc9c740"/>\n' + \
'      <fraction n="0.83789" ref="Cr520x7fed4fc9c780"/>\n' + \
'      <fraction n="0.09501" ref="Cr530x7fed4fc9c7c0"/>\n' + \
'      <fraction n="0.02365" ref="Cr540x7fed4fc9c800"/>\n' + \
'    </element>\n' + \
'    <isotope N="58" Z="28" name="Ni580x7fed4fc9d000">\n' + \
'      <atom unit="g/mole" value="57.9353"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="60" Z="28" name="Ni600x7fed4fc9d040">\n' + \
'      <atom unit="g/mole" value="59.9308"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="61" Z="28" name="Ni610x7fed4fc9d080">\n' + \
'      <atom unit="g/mole" value="60.9311"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="62" Z="28" name="Ni620x7fed4fc9d0c0">\n' + \
'      <atom unit="g/mole" value="61.9283"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="64" Z="28" name="Ni640x7fed4fc9d100">\n' + \
'      <atom unit="g/mole" value="63.928"/>\n' + \
'    </isotope>\n' + \
'    <element name="Nickel0x7fed4fc9ce50">\n' + \
'      <fraction n="0.680769" ref="Ni580x7fed4fc9d000"/>\n' + \
'      <fraction n="0.262231" ref="Ni600x7fed4fc9d040"/>\n' + \
'      <fraction n="0.011399" ref="Ni610x7fed4fc9d080"/>\n' + \
'      <fraction n="0.036345" ref="Ni620x7fed4fc9d0c0"/>\n' + \
'      <fraction n="0.009256" ref="Ni640x7fed4fc9d100"/>\n' + \
'    </element>\n' + \
'    <isotope N="92" Z="42" name="Mo920x7fed4fc9d3e0">\n' + \
'      <atom unit="g/mole" value="91.9068"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="94" Z="42" name="Mo940x7fed4fc9d420">\n' + \
'      <atom unit="g/mole" value="93.9051"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="95" Z="42" name="Mo950x7fed4fc9d460">\n' + \
'      <atom unit="g/mole" value="94.9058"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="96" Z="42" name="Mo960x7fed4fc9d4a0">\n' + \
'      <atom unit="g/mole" value="95.9047"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="97" Z="42" name="Mo970x7fed4fc9d4e0">\n' + \
'      <atom unit="g/mole" value="96.906"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="98" Z="42" name="Mo980x7fed4fc9d520">\n' + \
'      <atom unit="g/mole" value="97.9054"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="100" Z="42" name="Mo1000x7fed4fc9d560">\n' + \
'      <atom unit="g/mole" value="99.9075"/>\n' + \
'    </isotope>\n' + \
'    <element name="Molybdenum0x7fed4fc9d1e0">\n' + \
'      <fraction n="0.1484" ref="Mo920x7fed4fc9d3e0"/>\n' + \
'      <fraction n="0.0925" ref="Mo940x7fed4fc9d420"/>\n' + \
'      <fraction n="0.1592" ref="Mo950x7fed4fc9d460"/>\n' + \
'      <fraction n="0.1668" ref="Mo960x7fed4fc9d4a0"/>\n' + \
'      <fraction n="0.0955" ref="Mo970x7fed4fc9d4e0"/>\n' + \
'      <fraction n="0.2413" ref="Mo980x7fed4fc9d520"/>\n' + \
'      <fraction n="0.0963" ref="Mo1000x7fed4fc9d560"/>\n' + \
'    </element>\n' + \
'    <isotope N="14" Z="7" name="N140x7fed4fc9aac0">\n' + \
'      <atom unit="g/mole" value="14.0031"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="15" Z="7" name="N150x7fed4fc9ab00">\n' + \
'      <atom unit="g/mole" value="15.0001"/>\n' + \
'    </isotope>\n' + \
'    <element name="Nitrogen0x7fed4fc9a9c0">\n' + \
'      <fraction n="0.99632" ref="N140x7fed4fc9aac0"/>\n' + \
'      <fraction n="0.00368" ref="N150x7fed4fc9ab00"/>\n' + \
'    </element>\n' + \
'    <isotope N="54" Z="26" name="Fe540x7fed4fc9ccb0">\n' + \
'      <atom unit="g/mole" value="53.9396"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="56" Z="26" name="Fe560x7fed4fc9ccf0">\n' + \
'      <atom unit="g/mole" value="55.9349"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="57" Z="26" name="Fe570x7fed4fc9cd30">\n' + \
'      <atom unit="g/mole" value="56.9354"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="58" Z="26" name="Fe580x7fed4fc9cd70">\n' + \
'      <atom unit="g/mole" value="57.9333"/>\n' + \
'    </isotope>\n' + \
'    <element name="Iron0x7fed4fc9cb20">\n' + \
'      <fraction n="0.05845" ref="Fe540x7fed4fc9ccb0"/>\n' + \
'      <fraction n="0.91754" ref="Fe560x7fed4fc9ccf0"/>\n' + \
'      <fraction n="0.02119" ref="Fe570x7fed4fc9cd30"/>\n' + \
'      <fraction n="0.00282" ref="Fe580x7fed4fc9cd70"/>\n' + \
'    </element>\n' + \
'    <material name="ss_t3160x7fed4fc9ef60" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="284.208486931803"/>\n' + \
'      <D unit="g/cm3" value="8.03"/>\n' + \
'      <fraction n="0.0008" ref="Carbon0x7fed4fc9a830"/>\n' + \
'      <fraction n="0.02" ref="Manganese0x7fed4fc9c8e0"/>\n' + \
'      <fraction n="0.00045" ref="Phosphorus0x7fed4fc9bf80"/>\n' + \
'      <fraction n="0.0003" ref="Sulfur0x7fed4fc9c1a0"/>\n' + \
'      <fraction n="0.0075" ref="Silicon0x7fed4fc9bcc0"/>\n' + \
'      <fraction n="0.17" ref="Chromium0x7fed4fc9c600"/>\n' + \
'      <fraction n="0.12" ref="Nickel0x7fed4fc9ce50"/>\n' + \
'      <fraction n="0.025" ref="Molybdenum0x7fed4fc9d1e0"/>\n' + \
'      <fraction n="0.001" ref="Nitrogen0x7fed4fc9a9c0"/>\n' + \
'      <fraction n="0.65495" ref="Iron0x7fed4fc9cb20"/>\n' + \
'    </material>\n' + \
'    <isotope N="1" Z="1" name="H10x7fed4fc9e310">\n' + \
'      <atom unit="g/mole" value="1.00782503081372"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="2" Z="1" name="H20x7fed4fc9e800">\n' + \
'      <atom unit="g/mole" value="2.01410199966617"/>\n' + \
'    </isotope>\n' + \
'    <element name="H0x7fed4fc9e740">\n' + \
'      <fraction n="0.999885" ref="H10x7fed4fc9e310"/>\n' + \
'      <fraction n="0.000115" ref="H20x7fed4fc9e800"/>\n' + \
'    </element>\n' + \
'    <material name="galactic0x7fed4fc9e650" state="gas">\n' + \
'      <T unit="K" value="2.73"/>\n' + \
'      <P unit="pascal" value="3e-18"/>\n' + \
'      <MEE unit="eV" value="19.2"/>\n' + \
'      <D unit="g/cm3" value="1e-25"/>\n' + \
'      <fraction n="1" ref="H0x7fed4fc9e740"/>\n' + \
'    </material>\n' + \
'    <isotope N="63" Z="29" name="Cu630x7fed4fc9f420">\n' + \
'      <atom unit="g/mole" value="62.9296"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="65" Z="29" name="Cu650x7fed4fc9f460">\n' + \
'      <atom unit="g/mole" value="64.9278"/>\n' + \
'    </isotope>\n' + \
'    <element name="Cu0x7fed4fc9f350">\n' + \
'      <fraction n="0.6917" ref="Cu630x7fed4fc9f420"/>\n' + \
'      <fraction n="0.3083" ref="Cu650x7fed4fc9f460"/>\n' + \
'    </element>\n' + \
'    <material name="Cu0x7fed4fc9f260" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="322"/>\n' + \
'      <D unit="g/cm3" value="8.96"/>\n' + \
'      <fraction n="1" ref="Cu0x7fed4fc9f350"/>\n' + \
'    </material>\n' + \
'    <material Z="13" name="Al0x7fed4fca0a70" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="166"/>\n' + \
'      <D unit="g/cm3" value="2.7"/>\n' + \
'      <atom unit="g/mole" value="26.981538"/>\n' + \
'    </material>\n' + \
'    <isotope N="14" Z="7" name="N140x7fed4fc9db80">\n' + \
'      <atom unit="g/mole" value="14.0031"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="15" Z="7" name="N150x7fed4fc9e030">\n' + \
'      <atom unit="g/mole" value="15.0001"/>\n' + \
'    </isotope>\n' + \
'    <element name="N0x7fed4fc9df60">\n' + \
'      <fraction n="0.99632" ref="N140x7fed4fc9db80"/>\n' + \
'      <fraction n="0.00368" ref="N150x7fed4fc9e030"/>\n' + \
'    </element>\n' + \
'    <material name="liquid_nitrogen0x7fed4fc9de70" state="liquid">\n' + \
'      <T unit="K" value="77"/>\n' + \
'      <MEE unit="eV" value="82"/>\n' + \
'      <D unit="g/cm3" value="0.807"/>\n' + \
'      <fraction n="1" ref="N0x7fed4fc9df60"/>\n' + \
'    </material>\n' + \
'    <material name="G4_WATER0x7fed4fcaca90" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="78"/>\n' + \
'      <D unit="g/cm3" value="1"/>\n' + \
'      <fraction n="0.111898477841067" ref="H0x7fed4fc83f20"/>\n' + \
'      <fraction n="0.888101522158933" ref="O0x7fed4fc84fc0"/>\n' + \
'    </material>\n' + \
'    <isotope N="14" Z="7" name="N140x7fed4fc84be0">\n' + \
'      <atom unit="g/mole" value="14.0031"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="15" Z="7" name="N150x7fed4fc84c60">\n' + \
'      <atom unit="g/mole" value="15.0001"/>\n' + \
'    </isotope>\n' + \
'    <element name="N0x7fed4fc84cb0">\n' + \
'      <fraction n="0.99632" ref="N140x7fed4fc84be0"/>\n' + \
'      <fraction n="0.00368" ref="N150x7fed4fc84c60"/>\n' + \
'    </element>\n' + \
'    <isotope N="36" Z="18" name="Ar360x7fed4fc85150">\n' + \
'      <atom unit="g/mole" value="35.9675"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="38" Z="18" name="Ar380x7fed4fc85190">\n' + \
'      <atom unit="g/mole" value="37.9627"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="40" Z="18" name="Ar400x7fed4fc851e0">\n' + \
'      <atom unit="g/mole" value="39.9624"/>\n' + \
'    </isotope>\n' + \
'    <element name="Ar0x7fed4fc85220">\n' + \
'      <fraction n="0.003365" ref="Ar360x7fed4fc85150"/>\n' + \
'      <fraction n="0.000632" ref="Ar380x7fed4fc85190"/>\n' + \
'      <fraction n="0.996003" ref="Ar400x7fed4fc851e0"/>\n' + \
'    </element>\n' + \
'    <material name="Air0x7fed4fc84940" state="gas">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="85.7"/>\n' + \
'      <D unit="g/cm3" value="0.00120479"/>\n' + \
'      <fraction n="0.000124000124000124" ref="C0x7fed4fc84a30"/>\n' + \
'      <fraction n="0.755267755267755" ref="N0x7fed4fc84cb0"/>\n' + \
'      <fraction n="0.231781231781232" ref="O0x7fed4fc84fc0"/>\n' + \
'      <fraction n="0.0128270128270128" ref="Ar0x7fed4fc85220"/>\n' + \
'    </material>\n' + \
'  </materials>\n' + \
'\n' + \
'  <solids>\n' + \
'    <box lunit="mm" name="z_wall0x7fed4fcaf6b0" x="8648.7" y="8039.1" z="266.7"/>\n' + \
'    <box lunit="mm" name="x_wall_short0x7fed4fcafe40" x="6261.1" y="266.7" z="3759.2"/>\n' + \
'    <box lunit="mm" name="x_wall_long0x7fed4fcb02b0" x="7632.7" y="127" z="3759.2"/>\n' + \
'    <box lunit="mm" name="y_wall_left0x7fed4fcb06e0" x="266.7" y="6629.4" z="3759.2"/>\n' + \
'    <box lunit="mm" name="y_wall_right0x7fed4fcb0b20" x="152.4" y="4800.6" z="3759.2"/>\n' + \
'    <box lunit="mm" name="room_x_wall_adj_door_length0x7fed4fcb0f40" x="1219.2" y="152.4" z="3759.2"/>\n' + \
'    <box lunit="mm" name="cupboard_OV0x7fed4fcb1470" x="685.8" y="1511.3" z="914.4"/>\n' + \
'    <box lunit="mm" name="cupboard_IV0x7fed4fcb14e0" x="635" y="1460.5" z="863.6"/>\n' + \
'    <subtraction name="cupboard0x7fed4fcb1550">\n' + \
'      <first ref="cupboard_OV0x7fed4fcb1470"/>\n' + \
'      <second ref="cupboard_IV0x7fed4fcb14e0"/>\n' + \
'    </subtraction>\n' + \
'    <box lunit="mm" name="pump_room_OV0x7fed4dc46e20" x="1308.1" y="2590.8" z="3759.2"/>\n' + \
'    <box lunit="mm" name="pump_room_IV0x7fed4dc46ee0" x="1206.5" y="2489.2" z="3759.2"/>\n' + \
'    <subtraction name="pump_room0x7fed4dc46f50">\n' + \
'      <first ref="pump_room_OV0x7fed4dc46e20"/>\n' + \
'      <second ref="pump_room_IV0x7fed4dc46ee0"/>\n' + \
'    </subtraction>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="platform_pillar0x7fed4dc47540" rmax="127" rmin="0" startphi="0" z="2057.4"/>\n' + \
'    <xtru lunit="mm" name="platform_tri_pri0x7fed4c033800">\n' + \
'      <twoDimVertex x="-2057.4" y="-1257.3"/>\n' + \
'      <twoDimVertex x="-2057.4" y="1257.3"/>\n' + \
'      <twoDimVertex x="0" y="0"/>\n' + \
'      <section scalingFactor="1" xOffset="0" yOffset="0" zOrder="0" zPosition="-177.8"/>\n' + \
'      <section scalingFactor="1" xOffset="0" yOffset="0" zOrder="1" zPosition="177.8"/>\n' + \
'    </xtru>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="platform_hole0x7fed4dc48870" rmax="317.5" rmin="0" startphi="0" z="177.8"/>\n' + \
'    <subtraction name="platform0x7fed4dc48330">\n' + \
'      <first ref="platform_tri_pri0x7fed4c033800"/>\n' + \
'      <second ref="platform_hole0x7fed4dc48870"/>\n' + \
'      <position name="platform0x7fed4dc48330_pos" unit="mm" x="-1346.2" y="0" z="0"/>\n' + \
'    </subtraction>\n' + \
'    <box lunit="mm" name="world_box0x7fed4fcaf560" x="9664.7" y="9055.1" z="6324.6"/>\n' + \
'    <box lunit="mm" name="building_space0x7fed4f9a8f60" x="8648.7" y="8039.1" z="5308.6"/>\n' + \
'    <subtraction name="soil_space0x7fed4f9a9020">\n' + \
'      <first ref="world_box0x7fed4fcaf560"/>\n' + \
'      <second ref="building_space0x7fed4f9a8f60"/>\n' + \
'      <position name="soil_space0x7fed4f9a9020_pos" unit="mm" x="508" y="-508" z="508"/>\n' + \
'    </subtraction>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_sample_inner0x7fed4f9ab4f0" rmax="64" rmin="0" startphi="0" z="183"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_sample_outer0x7fed4f9ab070" rmax="65" rmin="0" startphi="0" z="193"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_4k_inner0x7fed4f9aac00" rmax="68.9" rmin="0" startphi="0" z="327"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_4k_outer0x7fed4f9aa790" rmax="70.5" rmin="0" startphi="0" z="337"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_77k_inner0x7fed4f9aa310" rmax="75" rmin="0" startphi="0" z="358"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_77k_outer0x7fed4f9a9e90" rmax="76.2" rmin="0" startphi="0" z="368"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_vacuum_inner0x7fed4f9a9a10" rmax="100.3" rmin="0" startphi="0" z="441"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_vacuum_outer0x7fed4f9a9590" rmax="101.6" rmin="0" startphi="0" z="451"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="arm_vacuum0x7fed4f9ab970" rmax="50.8" rmin="45.8" startphi="0" z="304.8"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="arm_77k0x7fed4f9abe00" rmax="44" rmin="39" startphi="0" z="300.8"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="arm_4k0x7fed4f9ac1f0" rmax="38" rmin="33" startphi="0" z="296.8"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_nitrogen0x7fed4f9ad690" rmax="179.2" rmin="152.4" startphi="0" z="736.6"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_4k_inner0x7fed4f9ae4d0" rmax="128.4" rmin="0" startphi="0" z="498"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_4k_outer0x7fed4f9ae010" rmax="133.4" rmin="0" startphi="0" z="508"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_77k_inner0x7fed4f9adb50" rmax="147.4" rmin="0" startphi="0" z="752"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_77k_outer0x7fed4f9ad1d0" rmax="184.2" rmin="0" startphi="0" z="762"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_vacuum_inner0x7fed4f9acd10" rmax="204.6" rmin="0" startphi="0" z="879"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_vacuum_outer0x7fed4f9ac740" rmax="209.6" rmin="0" startphi="0" z="889"/>\n' + \
'    <box lunit="mm" name="tslot_vert_10x7fed4f9ae8f0" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_vert_20x7fed4f9aed20" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_vert_30x7fed4f9af150" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_vert_40x7fed4f9af580" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_hor_10x7fed4f9af9b0" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_20x7fed4f9afde0" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_30x7fed4f9b0210" x="1371.9" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_40x7fed4f9b0640" x="1371.9" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_50x7fed4f9b0a70" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_60x7fed4f9b0ea0" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_70x7fed4f9b12d0" x="419.2" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_80x7fed4f9b1700" x="419.2" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="dose_box0x7fed4f9b2180" x="250" y="250" z="250"/>\n' + \
'  </solids>\n' + \
'\n' + \
'  <structure>\n' + \
'    <volume name="z_wall0x7fed4fcaf720">\n' + \
'      <materialref ref="G4_CONCRETE0x7fed4fca2da0"/>\n' + \
'      <solidref ref="z_wall0x7fed4fcaf6b0"/>\n' + \
'    </volume>\n' + \
'    <volume name="x_wall_short0x7fed4fcafee0">\n' + \
'      <materialref ref="G4_CONCRETE0x7fed4fca2da0"/>\n' + \
'      <solidref ref="x_wall_short0x7fed4fcafe40"/>\n' + \
'    </volume>\n' + \
'    <volume name="x_wall_long0x7fed4fcb0350">\n' + \
'      <materialref ref="G4_CONCRETE0x7fed4fca2da0"/>\n' + \
'      <solidref ref="x_wall_long0x7fed4fcb02b0"/>\n' + \
'    </volume>\n' + \
'    <volume name="y_wall_left0x7fed4fcb0780">\n' + \
'      <materialref ref="G4_CONCRETE0x7fed4fca2da0"/>\n' + \
'      <solidref ref="y_wall_left0x7fed4fcb06e0"/>\n' + \
'    </volume>\n' + \
'    <volume name="y_wall_right0x7fed4fcb0bd0">\n' + \
'      <materialref ref="G4_CONCRETE0x7fed4fca2da0"/>\n' + \
'      <solidref ref="y_wall_right0x7fed4fcb0b20"/>\n' + \
'    </volume>\n' + \
'    <volume name="room_x_wall_adj_door_length0x7fed4fcb1000">\n' + \
'      <materialref ref="G4_CONCRETE0x7fed4fca2da0"/>\n' + \
'      <solidref ref="room_x_wall_adj_door_length0x7fed4fcb0f40"/>\n' + \
'    </volume>\n' + \
'    <volume name="cupboard0x7fed4fcb1690">\n' + \
'      <materialref ref="wood0x7fed4fc97d30"/>\n' + \
'      <solidref ref="cupboard0x7fed4fcb1550"/>\n' + \
'    </volume>\n' + \
'    <volume name="pump_room0x7fed4dc47090">\n' + \
'      <materialref ref="wood0x7fed4fc97d30"/>\n' + \
'      <solidref ref="pump_room0x7fed4dc46f50"/>\n' + \
'    </volume>\n' + \
'    <volume name="platform_pillar0x7fed4dc47490">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="platform_pillar0x7fed4dc47540"/>\n' + \
'    </volume>\n' + \
'    <volume name="platform0x7fed4dc48630">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="platform0x7fed4dc48330"/>\n' + \
'    </volume>\n' + \
'    <volume name="soil_space0x7fed4f9a9160">\n' + \
'      <materialref ref="Soil0x7fed4fc96a70"/>\n' + \
'      <solidref ref="soil_space0x7fed4f9a9020"/>\n' + \
'    </volume>\n' + \
'    <volume name="can_sample_inner0x7fed4f9ab450">\n' + \
'      <materialref ref="liquid_helium0x7fed4fc9d640"/>\n' + \
'      <solidref ref="can_sample_inner0x7fed4f9ab4f0"/>\n' + \
'    </volume>\n' + \
'    <volume name="can_sample_outer0x7fed4f9aafc0">\n' + \
'      <materialref ref="ss_t3160x7fed4fc9ef60"/>\n' + \
'      <solidref ref="can_sample_outer0x7fed4f9ab070"/>\n' + \
'      <physvol name="can_sample_inner0x7fed4f9ab5d0">\n' + \
'        <volumeref ref="can_sample_inner0x7fed4f9ab450"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_4k_inner0x7fed4f9aab50">\n' + \
'      <materialref ref="galactic0x7fed4fc9e650"/>\n' + \
'      <solidref ref="can_4k_inner0x7fed4f9aac00"/>\n' + \
'      <physvol name="can_sample_outer0x7fed4f9ab150">\n' + \
'        <volumeref ref="can_sample_outer0x7fed4f9aafc0"/>\n' + \
'        <position name="can_sample_outer0x7fed4f9ab150_pos" unit="mm" x="0" y="0" z="59"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_4k_outer0x7fed4f9aa6e0">\n' + \
'      <materialref ref="Cu0x7fed4fc9f260"/>\n' + \
'      <solidref ref="can_4k_outer0x7fed4f9aa790"/>\n' + \
'      <physvol name="can_4k_inner0x7fed4f9aace0">\n' + \
'        <volumeref ref="can_4k_inner0x7fed4f9aab50"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_77k_inner0x7fed4f9aa260">\n' + \
'      <materialref ref="galactic0x7fed4fc9e650"/>\n' + \
'      <solidref ref="can_77k_inner0x7fed4f9aa310"/>\n' + \
'      <physvol name="can_4k_outer0x7fed4f9aa870">\n' + \
'        <volumeref ref="can_4k_outer0x7fed4f9aa6e0"/>\n' + \
'        <position name="can_4k_outer0x7fed4f9aa870_pos" unit="mm" x="0" y="0" z="2.5"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_77k_outer0x7fed4f9a9df0">\n' + \
'      <materialref ref="Cu0x7fed4fc9f260"/>\n' + \
'      <solidref ref="can_77k_outer0x7fed4f9a9e90"/>\n' + \
'      <physvol name="can_77k_inner0x7fed4f9aa3f0">\n' + \
'        <volumeref ref="can_77k_inner0x7fed4f9aa260"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_vacuum_inner0x7fed4f9a9970">\n' + \
'      <materialref ref="galactic0x7fed4fc9e650"/>\n' + \
'      <solidref ref="can_vacuum_inner0x7fed4f9a9a10"/>\n' + \
'      <physvol name="can_77k_outer0x7fed4f9a9f70">\n' + \
'        <volumeref ref="can_77k_outer0x7fed4f9a9df0"/>\n' + \
'        <position name="can_77k_outer0x7fed4f9a9f70_pos" unit="mm" x="0" y="0" z="28.5"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_vacuum_outer0x7fed4f9a94e0">\n' + \
'      <materialref ref="ss_t3160x7fed4fc9ef60"/>\n' + \
'      <solidref ref="can_vacuum_outer0x7fed4f9a9590"/>\n' + \
'      <physvol name="can_vacuum_inner0x7fed4f9a9af0">\n' + \
'        <volumeref ref="can_vacuum_inner0x7fed4f9a9970"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="arm_vacuum0x7fed4f9ab8d0">\n' + \
'      <materialref ref="ss_t3160x7fed4fc9ef60"/>\n' + \
'      <solidref ref="arm_vacuum0x7fed4f9ab970"/>\n' + \
'    </volume>\n' + \
'    <volume name="arm_77k0x7fed4f9abd50">\n' + \
'      <materialref ref="Al0x7fed4fca0a70"/>\n' + \
'      <solidref ref="arm_77k0x7fed4f9abe00"/>\n' + \
'    </volume>\n' + \
'    <volume name="arm_4k0x7fed4f9ac2e0">\n' + \
'      <materialref ref="Al0x7fed4fca0a70"/>\n' + \
'      <solidref ref="arm_4k0x7fed4f9ac1f0"/>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_nitrogen0x7fed4f9ad600">\n' + \
'      <materialref ref="liquid_nitrogen0x7fed4fc9de70"/>\n' + \
'      <solidref ref="cryo_nitrogen0x7fed4f9ad690"/>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_4k_inner0x7fed4f9ae430">\n' + \
'      <materialref ref="liquid_helium0x7fed4fc9d640"/>\n' + \
'      <solidref ref="cryo_4k_inner0x7fed4f9ae4d0"/>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_4k_outer0x7fed4f9adf80">\n' + \
'      <materialref ref="ss_t3160x7fed4fc9ef60"/>\n' + \
'      <solidref ref="cryo_4k_outer0x7fed4f9ae010"/>\n' + \
'      <physvol name="cryo_4k_inner0x7fed4f9ae5b0">\n' + \
'        <volumeref ref="cryo_4k_inner0x7fed4f9ae430"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_77k_inner0x7fed4f9adab0">\n' + \
'      <materialref ref="galactic0x7fed4fc9e650"/>\n' + \
'      <solidref ref="cryo_77k_inner0x7fed4f9adb50"/>\n' + \
'      <physvol name="cryo_4k_outer0x7fed4f9ae0f0">\n' + \
'        <volumeref ref="cryo_4k_outer0x7fed4f9adf80"/>\n' + \
'        <position name="cryo_4k_outer0x7fed4f9ae0f0_pos" unit="mm" x="0" y="0" z="25.4"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_77k_outer0x7fed4f9ad140">\n' + \
'      <materialref ref="ss_t3160x7fed4fc9ef60"/>\n' + \
'      <solidref ref="cryo_77k_outer0x7fed4f9ad1d0"/>\n' + \
'      <physvol name="cryo_nitrogen0x7fed4f9ad770">\n' + \
'        <volumeref ref="cryo_nitrogen0x7fed4f9ad600"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="cryo_77k_inner0x7fed4f9adc30">\n' + \
'        <volumeref ref="cryo_77k_inner0x7fed4f9adab0"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_vacuum_inner0x7fed4f9acc80">\n' + \
'      <materialref ref="galactic0x7fed4fc9e650"/>\n' + \
'      <solidref ref="cryo_vacuum_inner0x7fed4f9acd10"/>\n' + \
'      <physvol name="cryo_77k_outer0x7fed4f9ad2b0">\n' + \
'        <volumeref ref="cryo_77k_outer0x7fed4f9ad140"/>\n' + \
'        <position name="cryo_77k_outer0x7fed4f9ad2b0_pos" unit="mm" x="0" y="0" z="-38.1"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_vacuum_outer0x7fed4f9ac6a0">\n' + \
'      <materialref ref="ss_t3160x7fed4fc9ef60"/>\n' + \
'      <solidref ref="cryo_vacuum_outer0x7fed4f9ac740"/>\n' + \
'      <physvol name="cryo_vacuum_inner0x7fed4f9acdf0">\n' + \
'        <volumeref ref="cryo_vacuum_inner0x7fed4f9acc80"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_10x7fed4f9ae990">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_vert_10x7fed4f9ae8f0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_20x7fed4f9aedc0">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_vert_20x7fed4f9aed20"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_30x7fed4f9af1f0">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_vert_30x7fed4f9af150"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_40x7fed4f9af620">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_vert_40x7fed4f9af580"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_10x7fed4f9afa50">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_10x7fed4f9af9b0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_20x7fed4f9afe80">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_20x7fed4f9afde0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_30x7fed4f9b02b0">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_30x7fed4f9b0210"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_40x7fed4f9b06e0">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_40x7fed4f9b0640"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_50x7fed4f9b0b10">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_50x7fed4f9b0a70"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_60x7fed4f9b0f40">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_60x7fed4f9b0ea0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_70x7fed4f9b1370">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_70x7fed4f9b12d0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_80x7fed4f9b17a0">\n' + \
'      <materialref ref="Al60610x7fed4fc96d40"/>\n' + \
'      <solidref ref="tslot_hor_80x7fed4f9b1700"/>\n' + \
'    </volume>\n' + \
'    <volume name="dose_box_LV0x7fed4f9b21f0">\n' + \
'      <materialref ref="G4_WATER0x7fed4fcaca90"/>\n' + \
'      <solidref ref="dose_box0x7fed4f9b2180"/>\n' + \
'    </volume>\n' + \
'    <volume name="WorldLV0x7fed4fcaf5d0">\n' + \
'      <materialref ref="Air0x7fed4fc84940"/>\n' + \
'      <solidref ref="world_box0x7fed4fcaf560"/>\n' + \
'      <physvol name="z_wall_10x7fed4fcaf7e0">\n' + \
'        <volumeref ref="z_wall0x7fed4fcaf720"/>\n' + \
'        <position name="z_wall_10x7fed4fcaf7e0_pos" unit="mm" x="508" y="-508" z="2012.95"/>\n' + \
'      </physvol>\n' + \
'      <physvol copynumber="1" name="z_wall_20x7fed4fcafb40">\n' + \
'        <volumeref ref="z_wall0x7fed4fcaf720"/>\n' + \
'        <position name="z_wall_20x7fed4fcafb40_pos" unit="mm" x="508" y="-508" z="-2012.95"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="x_wall_short0x7fed4fcaff70">\n' + \
'        <volumeref ref="x_wall_short0x7fed4fcafee0"/>\n' + \
'        <position name="x_wall_short0x7fed4fcaff70_pos" unit="mm" x="-685.8" y="3378.2" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="x_wall_long0x7fed4fcb03e0">\n' + \
'        <volumeref ref="x_wall_long0x7fed4fcb0350"/>\n' + \
'        <position name="x_wall_long0x7fed4fcb03e0_pos" unit="mm" x="0" y="-3448.05" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="y_wall_left0x7fed4fcb0810">\n' + \
'        <volumeref ref="y_wall_left0x7fed4fcb0780"/>\n' + \
'        <position name="y_wall_left0x7fed4fcb0810_pos" unit="mm" x="-3683" y="-69.85" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="y_wall_right0x7fed4fcb0c60">\n' + \
'        <volumeref ref="y_wall_right0x7fed4fcb0bd0"/>\n' + \
'        <position name="y_wall_right0x7fed4fcb0c60_pos" unit="mm" x="2368.55" y="844.55" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="room_x_wall_adj_door_length0x7fed4fcb10c0">\n' + \
'        <volumeref ref="room_x_wall_adj_door_length0x7fed4fcb1000"/>\n' + \
'        <position name="room_x_wall_adj_door_length0x7fed4fcb10c0_pos" unit="mm" x="3054.35" y="-1479.55" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="cupboard0x7fed4fcb1720">\n' + \
'        <volumeref ref="cupboard0x7fed4fcb1690"/>\n' + \
'        <position name="cupboard0x7fed4fcb1720_pos" unit="mm" x="1949.45" y="2489.2" z="-1422.4"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="pump_room0x7fed4dc47120">\n' + \
'        <volumeref ref="pump_room0x7fed4dc47090"/>\n' + \
'        <position name="pump_room0x7fed4dc47120_pos" unit="mm" x="-2895.6" y="-2089.15" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="platform_pillar0x7fed4dc47620">\n' + \
'        <volumeref ref="platform_pillar0x7fed4dc47490"/>\n' + \
'        <position name="platform_pillar0x7fed4dc47620_pos" unit="mm" x="-1492.25" y="1758.95" z="-850.9"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="platform0x7fed4dc486c0">\n' + \
'        <volumeref ref="platform0x7fed4dc48630"/>\n' + \
'        <position name="platform0x7fed4dc486c0_pos" unit="mm" x="-1492.25" y="1758.95" z="355.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="soil_space0x7fed4f9a91f0">\n' + \
'        <volumeref ref="soil_space0x7fed4f9a9160"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="can_vacuum_outer0x7fed4f9a9670">\n' + \
'        <volumeref ref="can_vacuum_outer0x7fed4f9a94e0"/>\n' + \
'        <position name="can_vacuum_outer0x7fed4f9a9670_pos" unit="mm" x="31.75" y="970.8" z="-654.1"/>\n' + \
'        <rotation name="can_vacuum_outer0x7fed4f9a9670_rot" unit="deg" x="180" y="0" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="arm_vacuum0x7fed4f9aba50">\n' + \
'        <volumeref ref="arm_vacuum0x7fed4f9ab8d0"/>\n' + \
'        <position name="arm_vacuum0x7fed4f9aba50_pos" unit="mm" x="31.75" y="970.8" z="-276.2"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="arm_77k0x7fed4f9abee0">\n' + \
'        <volumeref ref="arm_77k0x7fed4f9abd50"/>\n' + \
'        <position name="arm_77k0x7fed4f9abee0_pos" unit="mm" x="31.75" y="970.8" z="-276.2"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="arm_4k0x7fed4f9ac370">\n' + \
'        <volumeref ref="arm_4k0x7fed4f9ac2e0"/>\n' + \
'        <position name="arm_4k0x7fed4f9ac370_pos" unit="mm" x="31.75" y="970.8" z="-276.2"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="cryo_vacuum_outer0x7fed4f9ac820">\n' + \
'        <volumeref ref="cryo_vacuum_outer0x7fed4f9ac6a0"/>\n' + \
'        <position name="cryo_vacuum_outer0x7fed4f9ac820_pos" unit="mm" x="31.75" y="970.8" z="320.7"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_10x7fed4f9aea20">\n' + \
'        <volumeref ref="tslot_vert_10x7fed4f9ae990"/>\n' + \
'        <position name="tslot_vert_10x7fed4f9aea20_pos" unit="mm" x="736.75" y="1675.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_20x7fed4f9aee50">\n' + \
'        <volumeref ref="tslot_vert_20x7fed4f9aedc0"/>\n' + \
'        <position name="tslot_vert_20x7fed4f9aee50_pos" unit="mm" x="736.75" y="265.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_30x7fed4f9af280">\n' + \
'        <volumeref ref="tslot_vert_30x7fed4f9af1f0"/>\n' + \
'        <position name="tslot_vert_30x7fed4f9af280_pos" unit="mm" x="-673.25" y="1675.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_40x7fed4f9af6b0">\n' + \
'        <volumeref ref="tslot_vert_40x7fed4f9af620"/>\n' + \
'        <position name="tslot_vert_40x7fed4f9af6b0_pos" unit="mm" x="-673.25" y="265.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_10x7fed4f9afae0">\n' + \
'        <volumeref ref="tslot_hor_10x7fed4f9afa50"/>\n' + \
'        <position name="tslot_hor_10x7fed4f9afae0_pos" unit="mm" x="736.75" y="970.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_20x7fed4f9aff10">\n' + \
'        <volumeref ref="tslot_hor_20x7fed4f9afe80"/>\n' + \
'        <position name="tslot_hor_20x7fed4f9aff10_pos" unit="mm" x="-673.25" y="970.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_30x7fed4f9b0340">\n' + \
'        <volumeref ref="tslot_hor_30x7fed4f9b02b0"/>\n' + \
'        <position name="tslot_hor_30x7fed4f9b0340_pos" unit="mm" x="31.75" y="1675.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_40x7fed4f9b0770">\n' + \
'        <volumeref ref="tslot_hor_40x7fed4f9b06e0"/>\n' + \
'        <position name="tslot_hor_40x7fed4f9b0770_pos" unit="mm" x="31.75" y="265.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_50x7fed4f9b0ba0">\n' + \
'        <volumeref ref="tslot_hor_50x7fed4f9b0b10"/>\n' + \
'        <position name="tslot_hor_50x7fed4f9b0ba0_pos" unit="mm" x="260.4" y="970.8" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_60x7fed4f9b0fd0">\n' + \
'        <volumeref ref="tslot_hor_60x7fed4f9b0f40"/>\n' + \
'        <position name="tslot_hor_60x7fed4f9b0fd0_pos" unit="mm" x="-196.9" y="970.8" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_70x7fed4f9b1400">\n' + \
'        <volumeref ref="tslot_hor_70x7fed4f9b1370"/>\n' + \
'        <position name="tslot_hor_70x7fed4f9b1400_pos" unit="mm" x="31.75" y="1199.45" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_80x7fed4f9b1830">\n' + \
'        <volumeref ref="tslot_hor_80x7fed4f9b17a0"/>\n' + \
'        <position name="tslot_hor_80x7fed4f9b1830_pos" unit="mm" x="31.75" y="742.15" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="dose_box_PV0x7fed4f9b2280">\n' + \
'        <volumeref ref="dose_box_LV0x7fed4f9b21f0"/>\n' + \
'        <position name="dose_box_PV0x7fed4f9b2280_pos" unit="mm" x="' + str(xpos) + '" y="' + str(ypos) + '" z="' + str(zpos) + '"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'  </structure>\n' + \
'\n' + \
'  <setup name="Default" version="1.0">\n' + \
'    <world ref="WorldLV0x7fed4fcaf5d0"/>\n' + \
'  </setup>\n' + \
'\n' + \
'</gdml>\n'
	f = open(dest + '/GDML Files/' + name + str(i) + ".gdml", "w")
	f.write(filetext)
	f.close()