# This file generates GDML files according to the coordinates provided by the
# 'Detector Coordinates.txt' file. The text to write out was generated by
# the 'GDML conversion' Jupyter notebook.
import numpy as np

dest = "/Users/AndyB/Documents/School/Berkeley/Simulations/LabDose/Scripts"

coords = np.loadtxt(dest + '/' + 'Detector Coordinates.txt', skiprows=2)
name = "BirgeLab"

for i in range(0, len(coords)):
	xpos = coords[i,0]
	ypos = coords[i,1]
	zpos = coords[i,2]

	filetext = '<?xml version="1.0" encoding="UTF-8" standalone="no" ?>\n' + \
'<gdml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://service-spi.web.cern.ch/service-spi/app/releases/GDML/schema/gdml.xsd">\n' + \
'\n' + \
'  <define/>\n' + \
'\n' + \
'  <materials>\n' + \
'    <isotope N="1" Z="1" name="H10x7fb299c9a2f0">\n' + \
'      <atom unit="g/mole" value="1.00782503081372"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="2" Z="1" name="H20x7fb299c9a4e0">\n' + \
'      <atom unit="g/mole" value="2.01410199966617"/>\n' + \
'    </isotope>\n' + \
'    <element name="H0x7fb299c9a520">\n' + \
'      <fraction n="0.999885" ref="H10x7fb299c9a2f0"/>\n' + \
'      <fraction n="0.000115" ref="H20x7fb299c9a4e0"/>\n' + \
'    </element>\n' + \
'    <isotope N="12" Z="6" name="C120x7fb299c9a840">\n' + \
'      <atom unit="g/mole" value="12"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="13" Z="6" name="C130x7fb299c9a8a0">\n' + \
'      <atom unit="g/mole" value="13.0034"/>\n' + \
'    </isotope>\n' + \
'    <element name="C0x7fb299c9aff0">\n' + \
'      <fraction n="0.9893" ref="C120x7fb299c9a840"/>\n' + \
'      <fraction n="0.0107" ref="C130x7fb299c9a8a0"/>\n' + \
'    </element>\n' + \
'    <isotope N="16" Z="8" name="O160x7fb299c9b420">\n' + \
'      <atom unit="g/mole" value="15.9949"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="17" Z="8" name="O170x7fb299c9b460">\n' + \
'      <atom unit="g/mole" value="16.9991"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="18" Z="8" name="O180x7fb299c9b4a0">\n' + \
'      <atom unit="g/mole" value="17.9992"/>\n' + \
'    </isotope>\n' + \
'    <element name="O0x7fb299c9b580">\n' + \
'      <fraction n="0.99757" ref="O160x7fb299c9b420"/>\n' + \
'      <fraction n="0.00038" ref="O170x7fb299c9b460"/>\n' + \
'      <fraction n="0.00205" ref="O180x7fb299c9b4a0"/>\n' + \
'    </element>\n' + \
'    <isotope N="23" Z="11" name="Na230x7fb299c9e580">\n' + \
'      <atom unit="g/mole" value="22.9898"/>\n' + \
'    </isotope>\n' + \
'    <element name="Na0x7fb299c9e9d0">\n' + \
'      <fraction n="1" ref="Na230x7fb299c9e580"/>\n' + \
'    </element>\n' + \
'    <isotope N="24" Z="12" name="Mg240x7fb299cada00">\n' + \
'      <atom unit="g/mole" value="23.985"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="25" Z="12" name="Mg250x7fb299cad3f0">\n' + \
'      <atom unit="g/mole" value="24.9858"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="26" Z="12" name="Mg260x7fb299cad430">\n' + \
'      <atom unit="g/mole" value="25.9826"/>\n' + \
'    </isotope>\n' + \
'    <element name="Mg0x7fb299cad490">\n' + \
'      <fraction n="0.7899" ref="Mg240x7fb299cada00"/>\n' + \
'      <fraction n="0.1" ref="Mg250x7fb299cad3f0"/>\n' + \
'      <fraction n="0.1101" ref="Mg260x7fb299cad430"/>\n' + \
'    </element>\n' + \
'    <isotope N="27" Z="13" name="Al270x7fb299c9dcd0">\n' + \
'      <atom unit="g/mole" value="26.9815"/>\n' + \
'    </isotope>\n' + \
'    <element name="Al0x7fb299c9e200">\n' + \
'      <fraction n="1" ref="Al270x7fb299c9dcd0"/>\n' + \
'    </element>\n' + \
'    <isotope N="28" Z="14" name="Si280x7fb299c9eba0">\n' + \
'      <atom unit="g/mole" value="27.9769"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="29" Z="14" name="Si290x7fb299c9ebe0">\n' + \
'      <atom unit="g/mole" value="28.9765"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="30" Z="14" name="Si300x7fb299c9ec30">\n' + \
'      <atom unit="g/mole" value="29.9738"/>\n' + \
'    </isotope>\n' + \
'    <element name="Si0x7fb299c9ec90">\n' + \
'      <fraction n="0.922296077703922" ref="Si280x7fb299c9eba0"/>\n' + \
'      <fraction n="0.0468319531680468" ref="Si290x7fb299c9ebe0"/>\n' + \
'      <fraction n="0.0308719691280309" ref="Si300x7fb299c9ec30"/>\n' + \
'    </element>\n' + \
'    <isotope N="39" Z="19" name="K390x7fb299caa620">\n' + \
'      <atom unit="g/mole" value="38.9637"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="40" Z="19" name="K400x7fb299caa660">\n' + \
'      <atom unit="g/mole" value="39.964"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="41" Z="19" name="K410x7fb299caa6a0">\n' + \
'      <atom unit="g/mole" value="40.9618"/>\n' + \
'    </isotope>\n' + \
'    <element name="K0x7fb299caa700">\n' + \
'      <fraction n="0.932581" ref="K390x7fb299caa620"/>\n' + \
'      <fraction n="0.000117" ref="K400x7fb299caa660"/>\n' + \
'      <fraction n="0.067302" ref="K410x7fb299caa6a0"/>\n' + \
'    </element>\n' + \
'    <isotope N="40" Z="20" name="Ca400x7fb299c9ee90">\n' + \
'      <atom unit="g/mole" value="39.9626"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="42" Z="20" name="Ca420x7fb299c9eed0">\n' + \
'      <atom unit="g/mole" value="41.9586"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="43" Z="20" name="Ca430x7fb299c9ef10">\n' + \
'      <atom unit="g/mole" value="42.9588"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="44" Z="20" name="Ca440x7fb299c9ef50">\n' + \
'      <atom unit="g/mole" value="43.9555"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="46" Z="20" name="Ca460x7fb299c9ef90">\n' + \
'      <atom unit="g/mole" value="45.9537"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="48" Z="20" name="Ca480x7fb299c9cff0">\n' + \
'      <atom unit="g/mole" value="47.9525"/>\n' + \
'    </isotope>\n' + \
'    <element name="Ca0x7fb299c9f1d0">\n' + \
'      <fraction n="0.96941" ref="Ca400x7fb299c9ee90"/>\n' + \
'      <fraction n="0.00647" ref="Ca420x7fb299c9eed0"/>\n' + \
'      <fraction n="0.00135" ref="Ca430x7fb299c9ef10"/>\n' + \
'      <fraction n="0.02086" ref="Ca440x7fb299c9ef50"/>\n' + \
'      <fraction n="4e-05" ref="Ca460x7fb299c9ef90"/>\n' + \
'      <fraction n="0.00187" ref="Ca480x7fb299c9cff0"/>\n' + \
'    </element>\n' + \
'    <isotope N="54" Z="26" name="Fe540x7fb299ca3b70">\n' + \
'      <atom unit="g/mole" value="53.9396"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="56" Z="26" name="Fe560x7fb299ca3670">\n' + \
'      <atom unit="g/mole" value="55.9349"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="57" Z="26" name="Fe570x7fb299ca36b0">\n' + \
'      <atom unit="g/mole" value="56.9354"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="58" Z="26" name="Fe580x7fb299ca3710">\n' + \
'      <atom unit="g/mole" value="57.9333"/>\n' + \
'    </isotope>\n' + \
'    <element name="Fe0x7fb299ca3750">\n' + \
'      <fraction n="0.05845" ref="Fe540x7fb299ca3b70"/>\n' + \
'      <fraction n="0.91754" ref="Fe560x7fb299ca3670"/>\n' + \
'      <fraction n="0.02119" ref="Fe570x7fb299ca36b0"/>\n' + \
'      <fraction n="0.00282" ref="Fe580x7fb299ca3710"/>\n' + \
'    </element>\n' + \
'    <material name="G4_CONCRETE0x7fb29c093280" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="135.2"/>\n' + \
'      <D unit="g/cm3" value="2.3"/>\n' + \
'      <fraction n="0.01" ref="H0x7fb299c9a520"/>\n' + \
'      <fraction n="0.001" ref="C0x7fb299c9aff0"/>\n' + \
'      <fraction n="0.529107" ref="O0x7fb299c9b580"/>\n' + \
'      <fraction n="0.016" ref="Na0x7fb299c9e9d0"/>\n' + \
'      <fraction n="0.002" ref="Mg0x7fb299cad490"/>\n' + \
'      <fraction n="0.033872" ref="Al0x7fb299c9e200"/>\n' + \
'      <fraction n="0.337021" ref="Si0x7fb299c9ec90"/>\n' + \
'      <fraction n="0.013" ref="K0x7fb299caa700"/>\n' + \
'      <fraction n="0.044" ref="Ca0x7fb299c9f1d0"/>\n' + \
'      <fraction n="0.014" ref="Fe0x7fb299ca3750"/>\n' + \
'    </material>\n' + \
'    <material name="wood0x7fb299cae2f0" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="67.1996868607977"/>\n' + \
'      <D unit="g/cm3" value="0.9"/>\n' + \
'      <fraction n="0.0915215132472401" ref="H0x7fb299c9a520"/>\n' + \
'      <fraction n="0.363188118343343" ref="O0x7fb299c9b580"/>\n' + \
'      <fraction n="0.545290368409417" ref="C0x7fb299c9aff0"/>\n' + \
'    </material>\n' + \
'    <material name="Al60610x7fb299cad300" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="166.28607227249"/>\n' + \
'      <D unit="g/cm3" value="2.7"/>\n' + \
'      <fraction n="0.98" ref="Al0x7fb299c9e200"/>\n' + \
'      <fraction n="0.01" ref="Mg0x7fb299cad490"/>\n' + \
'      <fraction n="0.006" ref="Si0x7fb299c9ec90"/>\n' + \
'      <fraction n="0.004" ref="Fe0x7fb299ca3750"/>\n' + \
'    </material>\n' + \
'    <material name="Soil0x7fb299cad030" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="112.098510188939"/>\n' + \
'      <D unit="g/cm3" value="1.5"/>\n' + \
'      <fraction n="0.021" ref="H0x7fb299c9a520"/>\n' + \
'      <fraction n="0.016" ref="C0x7fb299c9aff0"/>\n' + \
'      <fraction n="0.577" ref="O0x7fb299c9b580"/>\n' + \
'      <fraction n="0.05" ref="Al0x7fb299c9e200"/>\n' + \
'      <fraction n="0.271" ref="Si0x7fb299c9ec90"/>\n' + \
'      <fraction n="0.013" ref="K0x7fb299caa700"/>\n' + \
'      <fraction n="0.041" ref="Ca0x7fb299c9f1d0"/>\n' + \
'      <fraction n="0.011" ref="Fe0x7fb299ca3750"/>\n' + \
'    </material>\n' + \
'    <isotope N="3" Z="2" name="He30x7fb299cb3e20">\n' + \
'      <atom unit="g/mole" value="3.01692961808401"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="4" Z="2" name="He40x7fb299cb3e60">\n' + \
'      <atom unit="g/mole" value="4.00264393551385"/>\n' + \
'    </isotope>\n' + \
'    <element name="He0x7fb299cb3d10">\n' + \
'      <fraction n="1.36999949310019e-06" ref="He30x7fb299cb3e20"/>\n' + \
'      <fraction n="0.999998630000507" ref="He40x7fb299cb3e60"/>\n' + \
'    </element>\n' + \
'    <material name="liquid_helium0x7fb299cb3c00" state="liquid">\n' + \
'      <T unit="K" value="3"/>\n' + \
'      <MEE unit="eV" value="41.8"/>\n' + \
'      <D unit="g/cm3" value="0.141"/>\n' + \
'      <fraction n="1" ref="He0x7fb299cb3d10"/>\n' + \
'    </material>\n' + \
'    <isotope N="12" Z="6" name="C120x7fb299cb0ba0">\n' + \
'      <atom unit="g/mole" value="12"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="13" Z="6" name="C130x7fb299cb0ea0">\n' + \
'      <atom unit="g/mole" value="13.0034"/>\n' + \
'    </isotope>\n' + \
'    <element name="Carbon0x7fb299cb0df0">\n' + \
'      <fraction n="0.9893" ref="C120x7fb299cb0ba0"/>\n' + \
'      <fraction n="0.0107" ref="C130x7fb299cb0ea0"/>\n' + \
'    </element>\n' + \
'    <isotope N="55" Z="25" name="Mn550x7fb299cb3000">\n' + \
'      <atom unit="g/mole" value="54.938"/>\n' + \
'    </isotope>\n' + \
'    <element name="Manganese0x7fb299cb2ea0">\n' + \
'      <fraction n="1" ref="Mn550x7fb299cb3000"/>\n' + \
'    </element>\n' + \
'    <isotope N="31" Z="15" name="P310x7fb299cb2680">\n' + \
'      <atom unit="g/mole" value="30.9738"/>\n' + \
'    </isotope>\n' + \
'    <element name="Phosphorus0x7fb299cb2540">\n' + \
'      <fraction n="1" ref="P310x7fb299cb2680"/>\n' + \
'    </element>\n' + \
'    <isotope N="32" Z="16" name="S320x7fb299cb28c0">\n' + \
'      <atom unit="g/mole" value="31.9721"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="33" Z="16" name="S330x7fb299cb2900">\n' + \
'      <atom unit="g/mole" value="32.9715"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="34" Z="16" name="S340x7fb299cb2940">\n' + \
'      <atom unit="g/mole" value="33.9679"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="36" Z="16" name="S360x7fb299cb2980">\n' + \
'      <atom unit="g/mole" value="35.9671"/>\n' + \
'    </isotope>\n' + \
'    <element name="Sulfur0x7fb299cb2760">\n' + \
'      <fraction n="0.9493" ref="S320x7fb299cb28c0"/>\n' + \
'      <fraction n="0.0076" ref="S330x7fb299cb2900"/>\n' + \
'      <fraction n="0.0429" ref="S340x7fb299cb2940"/>\n' + \
'      <fraction n="0.0002" ref="S360x7fb299cb2980"/>\n' + \
'    </element>\n' + \
'    <isotope N="28" Z="14" name="Si280x7fb299cb23e0">\n' + \
'      <atom unit="g/mole" value="27.9769"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="29" Z="14" name="Si290x7fb299cb2420">\n' + \
'      <atom unit="g/mole" value="28.9765"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="30" Z="14" name="Si300x7fb299cb2460">\n' + \
'      <atom unit="g/mole" value="29.9738"/>\n' + \
'    </isotope>\n' + \
'    <element name="Silicon0x7fb299cb2280">\n' + \
'      <fraction n="0.922296077703922" ref="Si280x7fb299cb23e0"/>\n' + \
'      <fraction n="0.0468319531680468" ref="Si290x7fb299cb2420"/>\n' + \
'      <fraction n="0.0308719691280309" ref="Si300x7fb299cb2460"/>\n' + \
'    </element>\n' + \
'    <isotope N="50" Z="24" name="Cr500x7fb299cb2d00">\n' + \
'      <atom unit="g/mole" value="49.946"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="52" Z="24" name="Cr520x7fb299cb2d40">\n' + \
'      <atom unit="g/mole" value="51.9405"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="53" Z="24" name="Cr530x7fb299cb2d80">\n' + \
'      <atom unit="g/mole" value="52.9407"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="54" Z="24" name="Cr540x7fb299cb2dc0">\n' + \
'      <atom unit="g/mole" value="53.9389"/>\n' + \
'    </isotope>\n' + \
'    <element name="Chromium0x7fb299cb2bc0">\n' + \
'      <fraction n="0.04345" ref="Cr500x7fb299cb2d00"/>\n' + \
'      <fraction n="0.83789" ref="Cr520x7fb299cb2d40"/>\n' + \
'      <fraction n="0.09501" ref="Cr530x7fb299cb2d80"/>\n' + \
'      <fraction n="0.02365" ref="Cr540x7fb299cb2dc0"/>\n' + \
'    </element>\n' + \
'    <isotope N="58" Z="28" name="Ni580x7fb299cb35c0">\n' + \
'      <atom unit="g/mole" value="57.9353"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="60" Z="28" name="Ni600x7fb299cb3600">\n' + \
'      <atom unit="g/mole" value="59.9308"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="61" Z="28" name="Ni610x7fb299cb3640">\n' + \
'      <atom unit="g/mole" value="60.9311"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="62" Z="28" name="Ni620x7fb299cb3680">\n' + \
'      <atom unit="g/mole" value="61.9283"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="64" Z="28" name="Ni640x7fb299cb36c0">\n' + \
'      <atom unit="g/mole" value="63.928"/>\n' + \
'    </isotope>\n' + \
'    <element name="Nickel0x7fb299cb3410">\n' + \
'      <fraction n="0.680769" ref="Ni580x7fb299cb35c0"/>\n' + \
'      <fraction n="0.262231" ref="Ni600x7fb299cb3600"/>\n' + \
'      <fraction n="0.011399" ref="Ni610x7fb299cb3640"/>\n' + \
'      <fraction n="0.036345" ref="Ni620x7fb299cb3680"/>\n' + \
'      <fraction n="0.009256" ref="Ni640x7fb299cb36c0"/>\n' + \
'    </element>\n' + \
'    <isotope N="92" Z="42" name="Mo920x7fb299cb39a0">\n' + \
'      <atom unit="g/mole" value="91.9068"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="94" Z="42" name="Mo940x7fb299cb39e0">\n' + \
'      <atom unit="g/mole" value="93.9051"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="95" Z="42" name="Mo950x7fb299cb3a20">\n' + \
'      <atom unit="g/mole" value="94.9058"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="96" Z="42" name="Mo960x7fb299cb3a60">\n' + \
'      <atom unit="g/mole" value="95.9047"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="97" Z="42" name="Mo970x7fb299cb3aa0">\n' + \
'      <atom unit="g/mole" value="96.906"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="98" Z="42" name="Mo980x7fb299cb3ae0">\n' + \
'      <atom unit="g/mole" value="97.9054"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="100" Z="42" name="Mo1000x7fb299cb3b20">\n' + \
'      <atom unit="g/mole" value="99.9075"/>\n' + \
'    </isotope>\n' + \
'    <element name="Molybdenum0x7fb299cb37a0">\n' + \
'      <fraction n="0.1484" ref="Mo920x7fb299cb39a0"/>\n' + \
'      <fraction n="0.0925" ref="Mo940x7fb299cb39e0"/>\n' + \
'      <fraction n="0.1592" ref="Mo950x7fb299cb3a20"/>\n' + \
'      <fraction n="0.1668" ref="Mo960x7fb299cb3a60"/>\n' + \
'      <fraction n="0.0955" ref="Mo970x7fb299cb3aa0"/>\n' + \
'      <fraction n="0.2413" ref="Mo980x7fb299cb3ae0"/>\n' + \
'      <fraction n="0.0963" ref="Mo1000x7fb299cb3b20"/>\n' + \
'    </element>\n' + \
'    <isotope N="14" Z="7" name="N140x7fb299cb1080">\n' + \
'      <atom unit="g/mole" value="14.0031"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="15" Z="7" name="N150x7fb299cb10c0">\n' + \
'      <atom unit="g/mole" value="15.0001"/>\n' + \
'    </isotope>\n' + \
'    <element name="Nitrogen0x7fb299cb0f80">\n' + \
'      <fraction n="0.99632" ref="N140x7fb299cb1080"/>\n' + \
'      <fraction n="0.00368" ref="N150x7fb299cb10c0"/>\n' + \
'    </element>\n' + \
'    <isotope N="54" Z="26" name="Fe540x7fb299cb3270">\n' + \
'      <atom unit="g/mole" value="53.9396"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="56" Z="26" name="Fe560x7fb299cb32b0">\n' + \
'      <atom unit="g/mole" value="55.9349"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="57" Z="26" name="Fe570x7fb299cb32f0">\n' + \
'      <atom unit="g/mole" value="56.9354"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="58" Z="26" name="Fe580x7fb299cb3330">\n' + \
'      <atom unit="g/mole" value="57.9333"/>\n' + \
'    </isotope>\n' + \
'    <element name="Iron0x7fb299cb30e0">\n' + \
'      <fraction n="0.05845" ref="Fe540x7fb299cb3270"/>\n' + \
'      <fraction n="0.91754" ref="Fe560x7fb299cb32b0"/>\n' + \
'      <fraction n="0.02119" ref="Fe570x7fb299cb32f0"/>\n' + \
'      <fraction n="0.00282" ref="Fe580x7fb299cb3330"/>\n' + \
'    </element>\n' + \
'    <material name="ss_t3160x7fb299cb5520" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="284.208486931803"/>\n' + \
'      <D unit="g/cm3" value="8.03"/>\n' + \
'      <fraction n="0.0008" ref="Carbon0x7fb299cb0df0"/>\n' + \
'      <fraction n="0.02" ref="Manganese0x7fb299cb2ea0"/>\n' + \
'      <fraction n="0.00045" ref="Phosphorus0x7fb299cb2540"/>\n' + \
'      <fraction n="0.0003" ref="Sulfur0x7fb299cb2760"/>\n' + \
'      <fraction n="0.0075" ref="Silicon0x7fb299cb2280"/>\n' + \
'      <fraction n="0.17" ref="Chromium0x7fb299cb2bc0"/>\n' + \
'      <fraction n="0.12" ref="Nickel0x7fb299cb3410"/>\n' + \
'      <fraction n="0.025" ref="Molybdenum0x7fb299cb37a0"/>\n' + \
'      <fraction n="0.001" ref="Nitrogen0x7fb299cb0f80"/>\n' + \
'      <fraction n="0.65495" ref="Iron0x7fb299cb30e0"/>\n' + \
'    </material>\n' + \
'    <isotope N="1" Z="1" name="H10x7fb299cb48d0">\n' + \
'      <atom unit="g/mole" value="1.00782503081372"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="2" Z="1" name="H20x7fb299cb4dc0">\n' + \
'      <atom unit="g/mole" value="2.01410199966617"/>\n' + \
'    </isotope>\n' + \
'    <element name="H0x7fb299cb4d00">\n' + \
'      <fraction n="0.999885" ref="H10x7fb299cb48d0"/>\n' + \
'      <fraction n="0.000115" ref="H20x7fb299cb4dc0"/>\n' + \
'    </element>\n' + \
'    <material name="galactic0x7fb299cb4c10" state="gas">\n' + \
'      <T unit="K" value="2.73"/>\n' + \
'      <P unit="pascal" value="3e-18"/>\n' + \
'      <MEE unit="eV" value="19.2"/>\n' + \
'      <D unit="g/cm3" value="1e-25"/>\n' + \
'      <fraction n="1" ref="H0x7fb299cb4d00"/>\n' + \
'    </material>\n' + \
'    <isotope N="63" Z="29" name="Cu630x7fb299cb59e0">\n' + \
'      <atom unit="g/mole" value="62.9296"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="65" Z="29" name="Cu650x7fb299cb5a20">\n' + \
'      <atom unit="g/mole" value="64.9278"/>\n' + \
'    </isotope>\n' + \
'    <element name="Cu0x7fb299cb5910">\n' + \
'      <fraction n="0.6917" ref="Cu630x7fb299cb59e0"/>\n' + \
'      <fraction n="0.3083" ref="Cu650x7fb299cb5a20"/>\n' + \
'    </element>\n' + \
'    <material name="Cu0x7fb299cb5820" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="322"/>\n' + \
'      <D unit="g/cm3" value="8.96"/>\n' + \
'      <fraction n="1" ref="Cu0x7fb299cb5910"/>\n' + \
'    </material>\n' + \
'    <material Z="13" name="Al0x7fb299cb7030" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="166"/>\n' + \
'      <D unit="g/cm3" value="2.7"/>\n' + \
'      <atom unit="g/mole" value="26.981538"/>\n' + \
'    </material>\n' + \
'    <isotope N="14" Z="7" name="N140x7fb299cb4140">\n' + \
'      <atom unit="g/mole" value="14.0031"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="15" Z="7" name="N150x7fb299cb45f0">\n' + \
'      <atom unit="g/mole" value="15.0001"/>\n' + \
'    </isotope>\n' + \
'    <element name="N0x7fb299cb4520">\n' + \
'      <fraction n="0.99632" ref="N140x7fb299cb4140"/>\n' + \
'      <fraction n="0.00368" ref="N150x7fb299cb45f0"/>\n' + \
'    </element>\n' + \
'    <material name="liquid_nitrogen0x7fb299cb4430" state="liquid">\n' + \
'      <T unit="K" value="77"/>\n' + \
'      <MEE unit="eV" value="82"/>\n' + \
'      <D unit="g/cm3" value="0.807"/>\n' + \
'      <fraction n="1" ref="N0x7fb299cb4520"/>\n' + \
'    </material>\n' + \
'    <material name="G4_WATER0x7fb29c093680" state="solid">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="78"/>\n' + \
'      <D unit="g/cm3" value="1"/>\n' + \
'      <fraction n="0.111898477841067" ref="H0x7fb299c9a520"/>\n' + \
'      <fraction n="0.888101522158933" ref="O0x7fb299c9b580"/>\n' + \
'    </material>\n' + \
'    <isotope N="14" Z="7" name="N140x7fb299c9b1a0">\n' + \
'      <atom unit="g/mole" value="14.0031"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="15" Z="7" name="N150x7fb299c9b220">\n' + \
'      <atom unit="g/mole" value="15.0001"/>\n' + \
'    </isotope>\n' + \
'    <element name="N0x7fb299c9b270">\n' + \
'      <fraction n="0.99632" ref="N140x7fb299c9b1a0"/>\n' + \
'      <fraction n="0.00368" ref="N150x7fb299c9b220"/>\n' + \
'    </element>\n' + \
'    <isotope N="36" Z="18" name="Ar360x7fb299c9b710">\n' + \
'      <atom unit="g/mole" value="35.9675"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="38" Z="18" name="Ar380x7fb299c9b750">\n' + \
'      <atom unit="g/mole" value="37.9627"/>\n' + \
'    </isotope>\n' + \
'    <isotope N="40" Z="18" name="Ar400x7fb299c9b7a0">\n' + \
'      <atom unit="g/mole" value="39.9624"/>\n' + \
'    </isotope>\n' + \
'    <element name="Ar0x7fb299c9b7e0">\n' + \
'      <fraction n="0.003365" ref="Ar360x7fb299c9b710"/>\n' + \
'      <fraction n="0.000632" ref="Ar380x7fb299c9b750"/>\n' + \
'      <fraction n="0.996003" ref="Ar400x7fb299c9b7a0"/>\n' + \
'    </element>\n' + \
'    <material name="Air0x7fb299c9af00" state="gas">\n' + \
'      <T unit="K" value="293.15"/>\n' + \
'      <MEE unit="eV" value="85.7"/>\n' + \
'      <D unit="g/cm3" value="0.00120479"/>\n' + \
'      <fraction n="0.000124000124000124" ref="C0x7fb299c9aff0"/>\n' + \
'      <fraction n="0.755267755267755" ref="N0x7fb299c9b270"/>\n' + \
'      <fraction n="0.231781231781232" ref="O0x7fb299c9b580"/>\n' + \
'      <fraction n="0.0128270128270128" ref="Ar0x7fb299c9b7e0"/>\n' + \
'    </material>\n' + \
'  </materials>\n' + \
'\n' + \
'  <solids>\n' + \
'    <box lunit="mm" name="z_wall0x7fb299cb9430" x="8648.7" y="8039.1" z="266.7"/>\n' + \
'    <box lunit="mm" name="x_wall_short0x7fb299cb9670" x="6261.1" y="266.7" z="3759.2"/>\n' + \
'    <box lunit="mm" name="x_wall_long0x7fb299cb9840" x="7632.7" y="127" z="3759.2"/>\n' + \
'    <box lunit="mm" name="y_wall_left0x7fb299cbaa70" x="266.7" y="6629.4" z="3759.2"/>\n' + \
'    <box lunit="mm" name="y_wall_right0x7fb299cbac50" x="152.4" y="4800.6" z="3759.2"/>\n' + \
'    <box lunit="mm" name="room_x_wall_adj_door_length0x7fb299cbae00" x="1219.2" y="152.4" z="3759.2"/>\n' + \
'    <box lunit="mm" name="cupboard_OV0x7fb299cbb060" x="685.8" y="1511.3" z="914.4"/>\n' + \
'    <box lunit="mm" name="cupboard_IV0x7fb299cbb0d0" x="635" y="1460.5" z="863.6"/>\n' + \
'    <subtraction name="cupboard0x7fb299cbb140">\n' + \
'      <first ref="cupboard_OV0x7fb299cbb060"/>\n' + \
'      <second ref="cupboard_IV0x7fb299cbb0d0"/>\n' + \
'    </subtraction>\n' + \
'    <box lunit="mm" name="pump_room_OV0x7fb299f9f580" x="1308.1" y="2590.8" z="3759.2"/>\n' + \
'    <box lunit="mm" name="pump_room_IV0x7fb299f9f5f0" x="1206.5" y="2489.2" z="3759.2"/>\n' + \
'    <subtraction name="pump_room0x7fb299f9f660">\n' + \
'      <first ref="pump_room_OV0x7fb299f9f580"/>\n' + \
'      <second ref="pump_room_IV0x7fb299f9f5f0"/>\n' + \
'    </subtraction>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="platform_pillar0x7fb29c096140" rmax="127" rmin="0" startphi="0" z="2057.4"/>\n' + \
'    <xtru lunit="mm" name="platform_tri_pri0x7fb29a00d000">\n' + \
'      <twoDimVertex x="-2057.4" y="-1257.3"/>\n' + \
'      <twoDimVertex x="-2057.4" y="1257.3"/>\n' + \
'      <twoDimVertex x="0" y="0"/>\n' + \
'      <section scalingFactor="1" xOffset="0" yOffset="0" zOrder="0" zPosition="-177.8"/>\n' + \
'      <section scalingFactor="1" xOffset="0" yOffset="0" zOrder="1" zPosition="177.8"/>\n' + \
'    </xtru>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="platform_hole0x7fb299cbbb90" rmax="317.5" rmin="0" startphi="0" z="177.8"/>\n' + \
'    <subtraction name="platform0x7fb299cbbfa0">\n' + \
'      <first ref="platform_tri_pri0x7fb29a00d000"/>\n' + \
'      <second ref="platform_hole0x7fb299cbbb90"/>\n' + \
'      <position name="platform0x7fb299cbbfa0_pos" unit="mm" x="-1346.2" y="0" z="0"/>\n' + \
'    </subtraction>\n' + \
'    <box lunit="mm" name="world_box0x7fb299cb9bb0" x="9664.7" y="9055.1" z="6324.6"/>\n' + \
'    <box lunit="mm" name="building_space0x7fb299d05340" x="8648.7" y="8039.1" z="5308.6"/>\n' + \
'    <subtraction name="soil_space0x7fb299d053b0">\n' + \
'      <first ref="world_box0x7fb299cb9bb0"/>\n' + \
'      <second ref="building_space0x7fb299d05340"/>\n' + \
'      <position name="soil_space0x7fb299d053b0_pos" unit="mm" x="508" y="-508" z="508"/>\n' + \
'    </subtraction>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_sample_inner0x7fb299d06550" rmax="64" rmin="0" startphi="0" z="183"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_sample_outer0x7fb299d06330" rmax="65" rmin="0" startphi="0" z="193"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_4k_inner0x7fb299d06110" rmax="68.9" rmin="0" startphi="0" z="327"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_4k_outer0x7fb299d05ef0" rmax="70.5" rmin="0" startphi="0" z="337"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_77k_inner0x7fb299d05cd0" rmax="75" rmin="0" startphi="0" z="358"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_77k_outer0x7fb299d05ab0" rmax="76.2" rmin="0" startphi="0" z="368"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_vacuum_inner0x7fb299d05890" rmax="100.3" rmin="0" startphi="0" z="441"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="can_vacuum_outer0x7fb299d05680" rmax="101.6" rmin="0" startphi="0" z="451"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="arm_vacuum0x7fb299d06770" rmax="50.8" rmin="45.8" startphi="0" z="304.8"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="arm_77k0x7fb299d06980" rmax="44" rmin="39" startphi="0" z="300.8"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="arm_4k0x7fb299d06bc0" rmax="38" rmin="33" startphi="0" z="296.8"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_nitrogen0x7fb299d074f0" rmax="179.2" rmin="152.4" startphi="0" z="736.6"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_4k_inner0x7fb299d07b40" rmax="128.4" rmin="0" startphi="0" z="498"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_4k_outer0x7fb299d07930" rmax="133.4" rmin="0" startphi="0" z="508"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_77k_inner0x7fb299d07710" rmax="147.4" rmin="0" startphi="0" z="752"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_77k_outer0x7fb299d072d0" rmax="184.2" rmin="0" startphi="0" z="762"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_vacuum_inner0x7fb299d070b0" rmax="204.6" rmin="0" startphi="0" z="879"/>\n' + \
'    <tube aunit="deg" deltaphi="360" lunit="mm" name="cryo_vacuum_outer0x7fb299d06db0" rmax="209.6" rmin="0" startphi="0" z="889"/>\n' + \
'    <box lunit="mm" name="tslot_vert_10x7fb299d07d60" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_vert_20x7fb299d07f00" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_vert_30x7fb299d080a0" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_vert_40x7fb299d08240" x="38.1" y="38.1" z="2286"/>\n' + \
'    <box lunit="mm" name="tslot_hor_10x7fb299d083e0" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_20x7fb299d08580" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_30x7fb299d08720" x="1371.9" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_40x7fb299d088c0" x="1371.9" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_50x7fb299d08a60" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_60x7fb299d08c00" x="38.1" y="1448.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_70x7fb299d08da0" x="419.2" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="tslot_hor_80x7fb299d08f40" x="419.2" y="38.1" z="38.1"/>\n' + \
'    <box lunit="mm" name="dose_box0x7fb299d09700" x="250" y="250" z="250"/>\n' + \
'  </solids>\n' + \
'\n' + \
'  <structure>\n' + \
'    <volume name="z_wall0x7fb299cb94a0">\n' + \
'      <materialref ref="G4_CONCRETE0x7fb29c093280"/>\n' + \
'      <solidref ref="z_wall0x7fb299cb9430"/>\n' + \
'    </volume>\n' + \
'    <volume name="x_wall_short0x7fb299cb96e0">\n' + \
'      <materialref ref="G4_CONCRETE0x7fb29c093280"/>\n' + \
'      <solidref ref="x_wall_short0x7fb299cb9670"/>\n' + \
'    </volume>\n' + \
'    <volume name="x_wall_long0x7fb299cba940">\n' + \
'      <materialref ref="G4_CONCRETE0x7fb29c093280"/>\n' + \
'      <solidref ref="x_wall_long0x7fb299cb9840"/>\n' + \
'    </volume>\n' + \
'    <volume name="y_wall_left0x7fb299cbaae0">\n' + \
'      <materialref ref="G4_CONCRETE0x7fb29c093280"/>\n' + \
'      <solidref ref="y_wall_left0x7fb299cbaa70"/>\n' + \
'    </volume>\n' + \
'    <volume name="y_wall_right0x7fb299cbacc0">\n' + \
'      <materialref ref="G4_CONCRETE0x7fb29c093280"/>\n' + \
'      <solidref ref="y_wall_right0x7fb299cbac50"/>\n' + \
'    </volume>\n' + \
'    <volume name="room_x_wall_adj_door_length0x7fb299cbae90">\n' + \
'      <materialref ref="G4_CONCRETE0x7fb29c093280"/>\n' + \
'      <solidref ref="room_x_wall_adj_door_length0x7fb299cbae00"/>\n' + \
'    </volume>\n' + \
'    <volume name="cupboard0x7fb299cbb280">\n' + \
'      <materialref ref="wood0x7fb299cae2f0"/>\n' + \
'      <solidref ref="cupboard0x7fb299cbb140"/>\n' + \
'    </volume>\n' + \
'    <volume name="pump_room0x7fb299f9f7f0">\n' + \
'      <materialref ref="wood0x7fb299cae2f0"/>\n' + \
'      <solidref ref="pump_room0x7fb299f9f660"/>\n' + \
'    </volume>\n' + \
'    <volume name="platform_pillar0x7fb299cbb380">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="platform_pillar0x7fb29c096140"/>\n' + \
'    </volume>\n' + \
'    <volume name="platform0x7fb299cbc5a0">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="platform0x7fb299cbbfa0"/>\n' + \
'    </volume>\n' + \
'    <volume name="soil_space0x7fb299d05540">\n' + \
'      <materialref ref="Soil0x7fb299cad030"/>\n' + \
'      <solidref ref="soil_space0x7fb299d053b0"/>\n' + \
'    </volume>\n' + \
'    <volume name="can_sample_inner0x7fb299d06630">\n' + \
'      <materialref ref="liquid_helium0x7fb299cb3c00"/>\n' + \
'      <solidref ref="can_sample_inner0x7fb299d06550"/>\n' + \
'    </volume>\n' + \
'    <volume name="can_sample_outer0x7fb299d06410">\n' + \
'      <materialref ref="ss_t3160x7fb299cb5520"/>\n' + \
'      <solidref ref="can_sample_outer0x7fb299d06330"/>\n' + \
'      <physvol name="can_sample_inner0x7fb299d066f0">\n' + \
'        <volumeref ref="can_sample_inner0x7fb299d06630"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_4k_inner0x7fb299d061f0">\n' + \
'      <materialref ref="galactic0x7fb299cb4c10"/>\n' + \
'      <solidref ref="can_4k_inner0x7fb299d06110"/>\n' + \
'      <physvol name="can_sample_outer0x7fb299d064d0">\n' + \
'        <volumeref ref="can_sample_outer0x7fb299d06410"/>\n' + \
'        <position name="can_sample_outer0x7fb299d064d0_pos" unit="mm" x="0" y="0" z="59"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_4k_outer0x7fb299d05fd0">\n' + \
'      <materialref ref="Cu0x7fb299cb5820"/>\n' + \
'      <solidref ref="can_4k_outer0x7fb299d05ef0"/>\n' + \
'      <physvol name="can_4k_inner0x7fb299d062b0">\n' + \
'        <volumeref ref="can_4k_inner0x7fb299d061f0"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_77k_inner0x7fb299d05db0">\n' + \
'      <materialref ref="galactic0x7fb299cb4c10"/>\n' + \
'      <solidref ref="can_77k_inner0x7fb299d05cd0"/>\n' + \
'      <physvol name="can_4k_outer0x7fb299d06090">\n' + \
'        <volumeref ref="can_4k_outer0x7fb299d05fd0"/>\n' + \
'        <position name="can_4k_outer0x7fb299d06090_pos" unit="mm" x="0" y="0" z="2.5"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_77k_outer0x7fb299d05b90">\n' + \
'      <materialref ref="Cu0x7fb299cb5820"/>\n' + \
'      <solidref ref="can_77k_outer0x7fb299d05ab0"/>\n' + \
'      <physvol name="can_77k_inner0x7fb299d05e70">\n' + \
'        <volumeref ref="can_77k_inner0x7fb299d05db0"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_vacuum_inner0x7fb299d05970">\n' + \
'      <materialref ref="galactic0x7fb299cb4c10"/>\n' + \
'      <solidref ref="can_vacuum_inner0x7fb299d05890"/>\n' + \
'      <physvol name="can_77k_outer0x7fb299d05c50">\n' + \
'        <volumeref ref="can_77k_outer0x7fb299d05b90"/>\n' + \
'        <position name="can_77k_outer0x7fb299d05c50_pos" unit="mm" x="0" y="0" z="28.5"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="can_vacuum_outer0x7fb299d05760">\n' + \
'      <materialref ref="ss_t3160x7fb299cb5520"/>\n' + \
'      <solidref ref="can_vacuum_outer0x7fb299d05680"/>\n' + \
'      <physvol name="can_vacuum_inner0x7fb299d05a30">\n' + \
'        <volumeref ref="can_vacuum_inner0x7fb299d05970"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="arm_vacuum0x7fb299d06850">\n' + \
'      <materialref ref="ss_t3160x7fb299cb5520"/>\n' + \
'      <solidref ref="arm_vacuum0x7fb299d06770"/>\n' + \
'    </volume>\n' + \
'    <volume name="arm_77k0x7fb299d06a60">\n' + \
'      <materialref ref="Al0x7fb299cb7030"/>\n' + \
'      <solidref ref="arm_77k0x7fb299d06980"/>\n' + \
'    </volume>\n' + \
'    <volume name="arm_4k0x7fb299d06ca0">\n' + \
'      <materialref ref="Al0x7fb299cb7030"/>\n' + \
'      <solidref ref="arm_4k0x7fb299d06bc0"/>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_nitrogen0x7fb299d075d0">\n' + \
'      <materialref ref="liquid_nitrogen0x7fb299cb4430"/>\n' + \
'      <solidref ref="cryo_nitrogen0x7fb299d074f0"/>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_4k_inner0x7fb299d07c20">\n' + \
'      <materialref ref="liquid_helium0x7fb299cb3c00"/>\n' + \
'      <solidref ref="cryo_4k_inner0x7fb299d07b40"/>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_4k_outer0x7fb299d07a10">\n' + \
'      <materialref ref="ss_t3160x7fb299cb5520"/>\n' + \
'      <solidref ref="cryo_4k_outer0x7fb299d07930"/>\n' + \
'      <physvol name="cryo_4k_inner0x7fb299d07ce0">\n' + \
'        <volumeref ref="cryo_4k_inner0x7fb299d07c20"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_77k_inner0x7fb299d077f0">\n' + \
'      <materialref ref="galactic0x7fb299cb4c10"/>\n' + \
'      <solidref ref="cryo_77k_inner0x7fb299d07710"/>\n' + \
'      <physvol name="cryo_4k_outer0x7fb299d07ad0">\n' + \
'        <volumeref ref="cryo_4k_outer0x7fb299d07a10"/>\n' + \
'        <position name="cryo_4k_outer0x7fb299d07ad0_pos" unit="mm" x="0" y="0" z="25.4"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_77k_outer0x7fb299d073b0">\n' + \
'      <materialref ref="ss_t3160x7fb299cb5520"/>\n' + \
'      <solidref ref="cryo_77k_outer0x7fb299d072d0"/>\n' + \
'      <physvol name="cryo_nitrogen0x7fb299d07690">\n' + \
'        <volumeref ref="cryo_nitrogen0x7fb299d075d0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="cryo_77k_inner0x7fb299d078b0">\n' + \
'        <volumeref ref="cryo_77k_inner0x7fb299d077f0"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_vacuum_inner0x7fb299d07190">\n' + \
'      <materialref ref="galactic0x7fb299cb4c10"/>\n' + \
'      <solidref ref="cryo_vacuum_inner0x7fb299d070b0"/>\n' + \
'      <physvol name="cryo_77k_outer0x7fb299d07470">\n' + \
'        <volumeref ref="cryo_77k_outer0x7fb299d073b0"/>\n' + \
'        <position name="cryo_77k_outer0x7fb299d07470_pos" unit="mm" x="0" y="0" z="-38.1"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="cryo_vacuum_outer0x7fb299d06e90">\n' + \
'      <materialref ref="ss_t3160x7fb299cb5520"/>\n' + \
'      <solidref ref="cryo_vacuum_outer0x7fb299d06db0"/>\n' + \
'      <physvol name="cryo_vacuum_inner0x7fb299d07250">\n' + \
'        <volumeref ref="cryo_vacuum_inner0x7fb299d07190"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_10x7fb299d07dd0">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_vert_10x7fb299d07d60"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_20x7fb299d07f70">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_vert_20x7fb299d07f00"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_30x7fb299d08110">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_vert_30x7fb299d080a0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_vert_40x7fb299d082b0">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_vert_40x7fb299d08240"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_10x7fb299d08450">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_10x7fb299d083e0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_20x7fb299d085f0">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_20x7fb299d08580"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_30x7fb299d08790">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_30x7fb299d08720"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_40x7fb299d08930">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_40x7fb299d088c0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_50x7fb299d08ad0">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_50x7fb299d08a60"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_60x7fb299d08c70">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_60x7fb299d08c00"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_70x7fb299d08e10">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_70x7fb299d08da0"/>\n' + \
'    </volume>\n' + \
'    <volume name="tslot_hor_80x7fb299d08fb0">\n' + \
'      <materialref ref="Al60610x7fb299cad300"/>\n' + \
'      <solidref ref="tslot_hor_80x7fb299d08f40"/>\n' + \
'    </volume>\n' + \
'    <volume name="dose_box_LV0x7fb299d09770">\n' + \
'      <materialref ref="G4_WATER0x7fb29c093680"/>\n' + \
'      <solidref ref="dose_box0x7fb299d09700"/>\n' + \
'    </volume>\n' + \
'    <volume name="world_box0x7fb299cb9330">\n' + \
'      <materialref ref="Air0x7fb299c9af00"/>\n' + \
'      <solidref ref="world_box0x7fb299cb9bb0"/>\n' + \
'      <physvol name="z_wall_10x7fb299cb9560">\n' + \
'        <volumeref ref="z_wall0x7fb299cb94a0"/>\n' + \
'        <position name="z_wall_10x7fb299cb9560_pos" unit="mm" x="508" y="-508" z="2012.95"/>\n' + \
'      </physvol>\n' + \
'      <physvol copynumber="1" name="z_wall_20x7fb299cb9600">\n' + \
'        <volumeref ref="z_wall0x7fb299cb94a0"/>\n' + \
'        <position name="z_wall_20x7fb299cb9600_pos" unit="mm" x="508" y="-508" z="-2012.95"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="x_wall_short0x7fb299cb9770">\n' + \
'        <volumeref ref="x_wall_short0x7fb299cb96e0"/>\n' + \
'        <position name="x_wall_short0x7fb299cb9770_pos" unit="mm" x="-685.8" y="3378.2" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="x_wall_long0x7fb299cbaa00">\n' + \
'        <volumeref ref="x_wall_long0x7fb299cba940"/>\n' + \
'        <position name="x_wall_long0x7fb299cbaa00_pos" unit="mm" x="0" y="-3448.05" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="y_wall_left0x7fb299cbaba0">\n' + \
'        <volumeref ref="y_wall_left0x7fb299cbaae0"/>\n' + \
'        <position name="y_wall_left0x7fb299cbaba0_pos" unit="mm" x="-3683" y="-69.85" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="y_wall_right0x7fb299cbad80">\n' + \
'        <volumeref ref="y_wall_right0x7fb299cbacc0"/>\n' + \
'        <position name="y_wall_right0x7fb299cbad80_pos" unit="mm" x="2368.55" y="844.55" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="room_x_wall_adj_door_length0x7fb299cbaf80">\n' + \
'        <volumeref ref="room_x_wall_adj_door_length0x7fb299cbae90"/>\n' + \
'        <position name="room_x_wall_adj_door_length0x7fb299cbaf80_pos" unit="mm" x="3054.35" y="-1479.55" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="cupboard0x7fb299cbb310">\n' + \
'        <volumeref ref="cupboard0x7fb299cbb280"/>\n' + \
'        <position name="cupboard0x7fb299cbb310_pos" unit="mm" x="1949.45" y="2489.2" z="-1422.4"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="pump_room0x7fb299f9f880">\n' + \
'        <volumeref ref="pump_room0x7fb299f9f7f0"/>\n' + \
'        <position name="pump_room0x7fb299f9f880_pos" unit="mm" x="-2895.6" y="-2089.15" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="platform_pillar0x7fb299cbb440">\n' + \
'        <volumeref ref="platform_pillar0x7fb299cbb380"/>\n' + \
'        <position name="platform_pillar0x7fb299cbb440_pos" unit="mm" x="-1492.25" y="1758.95" z="-850.9"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="platform0x7fb299cbc2a0">\n' + \
'        <volumeref ref="platform0x7fb299cbc5a0"/>\n' + \
'        <position name="platform0x7fb299cbc2a0_pos" unit="mm" x="-1492.25" y="1758.95" z="355.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="soil_space0x7fb299d055d0">\n' + \
'        <volumeref ref="soil_space0x7fb299d05540"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="can_vacuum_outer0x7fb299d05820">\n' + \
'        <volumeref ref="can_vacuum_outer0x7fb299d05760"/>\n' + \
'        <position name="can_vacuum_outer0x7fb299d05820_pos" unit="mm" x="31.75" y="970.8" z="-654.1"/>\n' + \
'        <rotation name="can_vacuum_outer0x7fb299d05820_rot" unit="deg" x="180" y="0" z="0"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="arm_vacuum0x7fb299d06910">\n' + \
'        <volumeref ref="arm_vacuum0x7fb299d06850"/>\n' + \
'        <position name="arm_vacuum0x7fb299d06910_pos" unit="mm" x="31.75" y="970.8" z="-276.2"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="arm_77k0x7fb299d06b20">\n' + \
'        <volumeref ref="arm_77k0x7fb299d06a60"/>\n' + \
'        <position name="arm_77k0x7fb299d06b20_pos" unit="mm" x="31.75" y="970.8" z="-276.2"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="arm_4k0x7fb299d06d30">\n' + \
'        <volumeref ref="arm_4k0x7fb299d06ca0"/>\n' + \
'        <position name="arm_4k0x7fb299d06d30_pos" unit="mm" x="31.75" y="970.8" z="-276.2"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="cryo_vacuum_outer0x7fb299d06f20">\n' + \
'        <volumeref ref="cryo_vacuum_outer0x7fb299d06e90"/>\n' + \
'        <position name="cryo_vacuum_outer0x7fb299d06f20_pos" unit="mm" x="31.75" y="970.8" z="320.7"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_10x7fb299d07e90">\n' + \
'        <volumeref ref="tslot_vert_10x7fb299d07dd0"/>\n' + \
'        <position name="tslot_vert_10x7fb299d07e90_pos" unit="mm" x="736.75" y="1675.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_20x7fb299d08030">\n' + \
'        <volumeref ref="tslot_vert_20x7fb299d07f70"/>\n' + \
'        <position name="tslot_vert_20x7fb299d08030_pos" unit="mm" x="736.75" y="265.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_30x7fb299d081d0">\n' + \
'        <volumeref ref="tslot_vert_30x7fb299d08110"/>\n' + \
'        <position name="tslot_vert_30x7fb299d081d0_pos" unit="mm" x="-673.25" y="1675.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_vert_40x7fb299d08370">\n' + \
'        <volumeref ref="tslot_vert_40x7fb299d082b0"/>\n' + \
'        <position name="tslot_vert_40x7fb299d08370_pos" unit="mm" x="-673.25" y="265.8" z="-736.6"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_10x7fb299d08510">\n' + \
'        <volumeref ref="tslot_hor_10x7fb299d08450"/>\n' + \
'        <position name="tslot_hor_10x7fb299d08510_pos" unit="mm" x="736.75" y="970.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_20x7fb299d086b0">\n' + \
'        <volumeref ref="tslot_hor_20x7fb299d085f0"/>\n' + \
'        <position name="tslot_hor_20x7fb299d086b0_pos" unit="mm" x="-673.25" y="970.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_30x7fb299d08850">\n' + \
'        <volumeref ref="tslot_hor_30x7fb299d08790"/>\n' + \
'        <position name="tslot_hor_30x7fb299d08850_pos" unit="mm" x="31.75" y="1675.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_40x7fb299d089f0">\n' + \
'        <volumeref ref="tslot_hor_40x7fb299d08930"/>\n' + \
'        <position name="tslot_hor_40x7fb299d089f0_pos" unit="mm" x="31.75" y="265.8" z="425.45"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_50x7fb299d08b90">\n' + \
'        <volumeref ref="tslot_hor_50x7fb299d08ad0"/>\n' + \
'        <position name="tslot_hor_50x7fb299d08b90_pos" unit="mm" x="260.4" y="970.8" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_60x7fb299d08d30">\n' + \
'        <volumeref ref="tslot_hor_60x7fb299d08c70"/>\n' + \
'        <position name="tslot_hor_60x7fb299d08d30_pos" unit="mm" x="-196.9" y="970.8" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_70x7fb299d08ed0">\n' + \
'        <volumeref ref="tslot_hor_70x7fb299d08e10"/>\n' + \
'        <position name="tslot_hor_70x7fb299d08ed0_pos" unit="mm" x="31.75" y="1199.45" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="tslot_hor_80x7fb299d09070">\n' + \
'        <volumeref ref="tslot_hor_80x7fb299d08fb0"/>\n' + \
'        <position name="tslot_hor_80x7fb299d09070_pos" unit="mm" x="31.75" y="742.15" z="463.55"/>\n' + \
'      </physvol>\n' + \
'      <physvol name="dose_box_PV0x7fb299d09830">\n' + \
'        <volumeref ref="dose_box_LV0x7fb299d09770"/>\n' + \
'        <position name="dose_box_PV0x7fb299d09830_pos" unit="mm" x="31.75" y="1720.8" z="-745"/>\n' + \
'      </physvol>\n' + \
'    </volume>\n' + \
'  </structure>\n' + \
'\n' + \
'  <setup name="Default" version="1.0">\n' + \
'    <world ref="world_box0x7fb299cb9330"/>\n' + \
'  </setup>\n' + \
'\n' + \
'</gdml>\n' + \
	f = open(dest + '/GDML Files/' + name + str(i) + ".gdml", "w")
	f.write(filetext)
	f.close()